/* Bolo — Home Gujarati, conversations, script course, placement. */

/* Each phrase: textbook (t), natural (n), very casual (c). [gu, tr] — gu/tr may be G(m,f). */
const HOME = [
  { id: 'h01', sit: 'Around the house', en: 'What are you doing?', t: ['તમે શું કરી રહ્યા છો?', 'tame shuṁ karī rahyā chho?'], n: ['શું કરે છે?', 'shuṁ kare chhe?'], c: ['શું ચાલે છે?', 'shuṁ chāle chhe?'], note: 'To an elder, natural is શું કરો છો? The -રહ્યા form is correct but sounds like a news reader.' },
  { id: 'h02', sit: 'Coming & going', en: 'Where are you going?', t: ['તમે ક્યાં જાઓ છો?', 'tame kyāṁ jāo chho?'], n: ['ક્યાં જાય છે?', 'kyāṁ jāy chhe?'], c: ['ક્યાં ચાલ્યો? / ક્યાં ચાલી?', 'kyāṁ chālyo? / kyāṁ chālī?'], note: 'The casual form changes with the person you ask: ચાલ્યો to a boy or man, ચાલી to a girl or woman.' },
  { id: 'h03', sit: 'Mealtime', en: 'Did you eat?', t: ['તમે જમ્યા?', 'tame jamyā?'], n: ['જમી લીધું?', 'jamī līdhuṁ?'], c: ['ખાધું?', 'khādhuṁ?'], note: 'Grandparents ask this instead of “how are you?”. Answer: હા, જમી લીધું.' },
  { id: 'h04', sit: 'Around the house', en: 'Come here.', t: ['અહીં આવો.', 'ahīṁ āvo.'], n: ['અહીં આવ.', 'ahīṁ āv.'], c: ['આમ આવ.', 'ām āv.'], note: 'આમ = “this way”. Very common at home.' },
  { id: 'h05', sit: 'Around the house', en: 'Wait.', t: ['રાહ જુઓ.', 'rāh juo.'], n: ['એક મિનિટ, ઊભા રહો.', 'ek miniṭ, ūbhā raho.'], c: ['ઊભો રહે! / ઊભી રહે!', 'ūbho rahe! / ūbhī rahe!'], note: 'Literally “stay standing”. ઊભો રહે to a boy or man, ઊભી રહે to a girl or woman — it follows the listener.' },
  { id: 'h06', sit: 'Feelings', en: 'What happened?', t: ['શું થયું?', 'shuṁ thayuṁ?'], n: ['શું થયું?', 'shuṁ thayuṁ?'], c: ['હવે શું થયું?', 'have shuṁ thayuṁ?'], note: 'Same in every register. હવે (“now”) adds an eye-roll: “what now?”' },
  { id: 'h07', sit: 'Around the house', en: 'Did you finish?', t: ['તમે પૂરું કર્યું?', 'tame pūruṁ karyuṁ?'], n: ['પતી ગયું?', 'patī gayuṁ?'], c: ['પત્યું?', 'patyuṁ?'], note: 'પતવું = to get finished. Homework, cooking, a phone call — anything.' },
  { id: 'h08', sit: 'Around the house', en: 'Go get this. / Bring that.', t: ['જાઓ, આ લઈ આવો.', 'jāo, ā laī āvo.'], n: ['જા, આ લઈ આવ.', 'jā, ā laī āv.'], c: ['આ લાવ તો.', 'ā lāv to.'], note: 'લઈ આવ = “take and come” = fetch. તો softens it.' },
  { id: 'h09', sit: 'Coming & going', en: 'I’m coming.', t: ['હું આવું છું.', 'huṁ āvuṁ chhuṁ.'], n: ['આવું છું!', 'āvuṁ chhuṁ!'], c: [G('આ આવ્યો!', 'આ આવી!'), G('ā āvyo!', 'ā āvī!')], note: 'The casual one is past tense (“here, I came!”) but means “on my way this second”.' },
  { id: 'h10', sit: 'Feelings', en: 'I’m tired.', t: [G('હું થાકી ગયો છું.', 'હું થાકી ગઈ છું.'), G('huṁ thākī gayo chhuṁ.', 'huṁ thākī gaī chhuṁ.')], n: [G('થાકી ગયો.', 'થાકી ગઈ.'), G('thākī gayo.', 'thākī gaī.')], c: [G('બહુ થાકી ગયો યાર.', 'બહુ થાકી ગઈ યાર.'), G('bahu thākī gayo yār.', 'bahu thākī gaī yār.')], note: 'Uses your gender. યાર only with friends and siblings.' },
  { id: 'h11', sit: 'Asking & answering', en: 'What do you want?', t: ['તમારે શું જોઈએ છે?', 'tamāre shuṁ joīe chhe?'], n: ['શું જોઈએ?', 'shuṁ joīe?'], c: ['બોલ, શું જોઈએ?', 'bol, shuṁ joīe?'], note: 'બોલ (“speak”) at the start means “go on, tell me”.' },
  { id: 'h12', sit: 'Asking & answering', en: 'Did you call them?', t: ['શું તમે એમને ફોન કર્યો?', 'shuṁ tame emne fon karyo?'], n: ['એમને ફોન કર્યો?', 'emne fon karyo?'], c: ['ફોન કર્યો કે નહીં?', 'fon karyo ke nahīṁ?'], note: 'ફોન is masculine, so the verb is કર્યો. … કે નહીં? = “… or not?” — a gentle nag.' },
  { id: 'h13', sit: 'Asking & answering', en: 'Where is it?', t: ['તે ક્યાં છે?', 'te kyāṁ chhe?'], n: ['ક્યાં છે?', 'kyāṁ chhe?'], c: ['ક્યાં મૂક્યું?', 'kyāṁ mūkyuṁ?'], note: 'The casual version asks “where did you put it?” — usually said while looking at you.' },
  { id: 'h14', sit: 'Coming & going', en: 'Let’s go.', t: ['ચાલો, આપણે જઈએ.', 'chālo, āpaṇe jaīe.'], n: ['ચાલો, જઈએ.', 'chālo, jaīe.'], c: ['ચલ!', 'chal!'], note: 'ચલ is to one person you’re close to. ચાલો works for everyone.' },
  { id: 'h15', sit: 'Mealtime', en: 'I’m hungry.', t: ['મને ભૂખ લાગી છે.', 'mane bhūkh lāgī chhe.'], n: ['ભૂખ લાગી છે.', 'bhūkh lāgī chhe.'], c: ['બહુ ભૂખ લાગી!', 'bahu bhūkh lāgī!'], note: 'Drop મને and even છે in casual speech.' },
  { id: 'h16', sit: 'Mealtime', en: 'Come and eat.', t: ['જમવાનું તૈયાર છે, આવો.', 'jamvānuṁ taiyār chhe, āvo.'], n: ['જમવા ચાલો!', 'jamvā chālo!'], c: ['ચાલો, જમવા!', 'chālo, jamvā!'], note: 'Reply: આવું છું! or આ આવ્યો / આ આવી!' },
  { id: 'h17', sit: 'Asking & answering', en: 'I don’t know.', t: ['મને ખબર નથી.', 'mane khabar nathī.'], n: ['ખબર નથી.', 'khabar nathī.'], c: ['શું ખબર!', 'shuṁ khabar!'], note: 'શું ખબર = “who knows!” with a shrug.' },
  { id: 'h18', sit: 'Coming & going', en: 'Hurry up.', t: ['જલદી કરો.', 'jaldī karo.'], n: ['જલદી કર!', 'jaldī kar!'], c: ['ચાલ ને, જલદી!', 'chāl ne, jaldī!'], note: 'જલદી = quickly.' },
  { id: 'h19', sit: 'Coming & going', en: 'Be careful.', t: ['ધ્યાન રાખો.', 'dhyān rākho.'], n: ['ધ્યાન રાખજે.', 'dhyān rākhje.'], c: ['સંભાળીને!', 'sambhāḷīne!'], note: 'Every Gujarati parent says ધ્યાન રાખજે when you leave the house.' },
  { id: 'h20', sit: 'Around the house', en: 'Go to sleep.', t: ['સૂઈ જાઓ.', 'sūī jāo.'], n: ['સૂઈ જા.', 'sūī jā.'], c: ['ચાલ, સૂઈ જા હવે.', 'chāl, sūī jā have.'], note: 'હવે at the end = “already, now”.' },
  { id: 'h21', sit: 'Around the house', en: 'Wake up!', t: ['ઊઠો.', 'ūṭho.'], n: ['ઊઠ!', 'ūṭh!'], c: ['ઊઠ, મોડું થાય છે!', 'ūṭh, moḍuṁ thāy chhe!'], note: 'મોડું થાય છે = it’s getting late.' },
  { id: 'h22', sit: 'Around the house', en: 'Turn off the light.', t: ['લાઇટ બંધ કરો.', 'lāiṭ bandh karo.'], n: ['લાઇટ બંધ કર.', 'lāiṭ bandh kar.'], c: ['લાઇટ બંધ કર ને.', 'lāiṭ bandh kar ne.'], note: 'બંધ કરવું = to turn off / close. ચાલુ કરવું = to turn on.' },
  { id: 'h23', sit: 'Mealtime', en: 'What’s cooking today?', t: ['આજે જમવામાં શું છે?', 'āje jamvāmāṁ shuṁ chhe?'], n: ['આજે શું બનાવ્યું છે?', 'āje shuṁ banāvyuṁ chhe?'], c: ['આજે શું છે ખાવામાં?', 'āje shuṁ chhe khāvāmāṁ?'], note: 'બનાવવું = to make. મમ્મી, આજે શું બનાવ્યું છે? is the classic.' },
  { id: 'h24', sit: 'Feelings', en: 'Did you like it?', t: ['તમને ગમ્યું?', 'tamne gamyuṁ?'], n: ['ગમ્યું?', 'gamyuṁ?'], c: ['કેવું લાગ્યું?', 'kevuṁ lāgyuṁ?'], note: 'કેવું લાગ્યું = “how did it seem?” — invites a real answer.' },
  { id: 'h25', sit: 'Asking & answering', en: 'I’ll do it later.', t: ['હું પછી કરીશ.', 'huṁ pachhī karīsh.'], n: ['પછી કરું છું.', 'pachhī karuṁ chhuṁ.'], c: ['હા, કરું છું, કરું છું!', 'hā, karuṁ chhuṁ, karuṁ chhuṁ!'], note: 'The doubled casual answer is what every teenager says. Use with care.' },
  { id: 'h26', sit: 'Feelings', en: 'Don’t worry.', t: ['ચિંતા ન કરો.', 'chintā na karo.'], n: ['ચિંતા ન કર.', 'chintā na kar.'], c: ['ટેન્શન ના લે.', 'ṭenshan nā le.'], note: 'Gujlish (Gujarati + English) is completely normal at home.' },
  { id: 'h27', sit: 'Feelings', en: 'It’s okay. / Never mind.', t: ['કોઈ વાંધો નહીં.', 'koī vāṁdho nahīṁ.'], n: ['વાંધો નહીં.', 'vāṁdho nahīṁ.'], c: ['ચાલશે.', 'chālshe.'], note: 'ચાલશે (“it’ll walk”) is maybe the most Gujarati word of all.' },
  { id: 'h28', sit: 'Around the house', en: 'Pass me that.', t: ['તે મને આપો.', 'te mane āpo.'], n: ['પેલું આપ ને.', 'peluṁ āp ne.'], c: ['ઓલું આપ તો.', 'oluṁ āp to.'], note: 'ઓલું (“that one”) is common in Saurashtra and in many diaspora homes; elsewhere people say પેલું.' },
];
const HOME_SITS = ['Around the house', 'Mealtime', 'Coming & going', 'Asking & answering', 'Feelings'];

/* Conversation scenarios. Turns alternate; a turn is either {npc:[gu,tr,en]} or {you:prompt, o:[[gu,tr,en,ok,why]], keys:[[...],...]}.
   keys = groups of Gujarati fragments; free answers must hit most groups. */
const SCENARIOS = [
  { id: 'meet', title: 'Meeting someone new', gu: 'નવી ઓળખાણ', who: 'friend', lvl: 1, where: 'A family party', goal: 'Introduce yourself and say where your family is from.',
    turns: [
      { npc: ['નમસ્તે! તમારું નામ શું છે?', 'namaste! tamāruṁ nām shuṁ chhe?', 'Hi! What’s your name?'] },
      { you: 'Say your name and ask hers.', o: [['મારું નામ નીલ છે. તમારું?', 'māruṁ nām nīl chhe. tamāruṁ?', 'My name is Neel. Yours?', true, 'Swap in your own name when you say it aloud.'], ['તમારું નામ નીલ છે.', 'tamāruṁ nām nīl chhe.', 'Your name is Neel.', false, 'That tells her *her* name. Use મારું (my).']], keys: [['મારું', 'નામ']] },
      { npc: ['મારું નામ પ્રિયા છે. તમે ક્યાંથી છો?', 'māruṁ nām priyā chhe. tame kyāṁthī chho?', 'I’m Priya. Where are you from?'] },
      { you: 'Say you’re from America, but your family is from Surat.', o: [['હું અમેરિકાથી છું, પણ મારો પરિવાર સુરતનો છે.', 'huṁ amerikāthī chhuṁ, paṇ māro parivār suratno chhe.', 'I’m from America, but my family is from Surat.', true, 'પરિવાર is masculine → મારો … સુરતનો.'], ['હું સુરત છું.', 'huṁ surat chhuṁ.', 'I am Surat.', false, 'Add -થી (from): સુરતથી.']], keys: [['થી', 'અમેરિકા', 'સુરત', 'અમદાવાદ', 'વડોદરા', 'રાજકોટ']] },
      { npc: ['અરે વાહ! તમે સરસ ગુજરાતી બોલો છો.', 'are vāh! tame saras gujarātī bolo chho.', 'Oh wow! You speak Gujarati well.'] },
      { you: 'Thank her and say you’re still learning.', o: [['આભાર! હું હજી શીખું છું.', 'ābhār! huṁ hajī shīkhuṁ chhuṁ.', 'Thanks! I’m still learning.', true, 'Humble and natural.'], ['હા, હું સરસ છું.', 'hā, huṁ saras chhuṁ.', 'Yes, I am great.', false, 'A bit much!']], keys: [['આભાર', 'થેંક્યુ'], ['શીખું', 'શીખી', 'શીખ']] },
    ] },
  { id: 'dinner', title: 'What’s for dinner?', gu: 'આજે શું બનાવ્યું છે?', who: 'mummy', lvl: 1, where: 'The kitchen, 7 pm', goal: 'Ask what’s cooking, react, and politely stop eating.',
    turns: [
      { you: 'Ask Mummy what she made today.', o: [['મમ્મી, આજે શું બનાવ્યું છે?', 'mammī, āje shuṁ banāvyuṁ chhe?', 'Mummy, what did you make today?', true, 'The classic line.'], ['મમ્મી, તમે ક્યાં છો?', 'mammī, tame kyāṁ chho?', 'Mummy, where are you?', false, 'She’s right there.']], keys: [['શું'], ['બનાવ્યું', 'જમવા', 'ખાવા', 'જમવામાં']] },
      { npc: ['આજે દાળ, ભાત, શાક ને રોટલી છે.', 'āje dāḷ, bhāt, shāk ne roṭlī chhe.', 'Today it’s dal, rice, shaak and rotli.'] },
      { you: 'Say you’re really hungry.', o: [['વાહ! મને બહુ ભૂખ લાગી છે.', 'vāh! mane bahu bhūkh lāgī chhe.', 'Great! I’m really hungry.', true, 'Hunger strikes you: મને ભૂખ લાગી છે.'], ['હું બહુ ભૂખ છું.', 'huṁ bahu bhūkh chhuṁ.', 'I am very hunger.', false, 'Say મને ભૂખ લાગી છે.']], keys: [['ભૂખ']] },
      { npc: ['તો જા, હાથ ધોઈ આવ. પછી જમવા બેસ.', 'to jā, hāth dhoī āv. pachhī jamvā bes.', 'Then go wash your hands. Then sit down to eat.'] },
      { you: 'Tell her you’re coming right away.', o: [['હમણાં આવું છું!', 'hamṇāṁ āvuṁ chhuṁ!', 'Coming right now!', true, 'Natural.'], [G('આ આવ્યો!', 'આ આવી!'), G('ā āvyo!', 'ā āvī!'), 'Coming!', true, 'Very natural at home.'], ['હું કાલે આવીશ.', 'huṁ kāle āvīsh.', 'I’ll come tomorrow.', false, 'Dinner won’t wait that long.']], keys: [['આવું', 'આવ્યો', 'આવી']] },
      { npc: ['શાક કેવું છે? તીખું તો નથી ને?', 'shāk kevuṁ chhe? tīkhuṁ to nathī ne?', 'How’s the shaak? Not too spicy, is it?'] },
      { you: 'Say it’s really good.', o: [['ના, બહુ સરસ છે!', 'nā, bahu saras chhe!', 'No, it’s really good!', true, 'She’ll be pleased.'], ['થોડું તીખું છે, પણ સરસ છે.', 'thoḍuṁ tīkhuṁ chhe, paṇ saras chhe.', 'A little spicy, but good.', true, 'Honest and kind.'], ['શાક ક્યાં છે?', 'shāk kyāṁ chhe?', 'Where is the shaak?', false, 'It’s on your plate.']], keys: [['સરસ', 'મસ્ત', 'સારું', 'તીખું']] },
      { npc: ['સારું, બીજી રોટલી લે.', 'sāruṁ, bījī roṭlī le.', 'Good, have another rotli.'] },
      { you: 'Politely say you’re full.', o: [['ના, બસ. પેટ ભરાઈ ગયું.', 'nā, bas. peṭ bharāī gayuṁ.', 'No, that’s enough. I’m full.', true, 'પેટ ભરાઈ ગયું = “my stomach got filled”.'], ['એક જ, બસ.', 'ek ja, bas.', 'Just one, that’s it.', true, 'A compromise every mother accepts.'], ['હું રોટલી છું.', 'huṁ roṭlī chhuṁ.', 'I am a rotli.', false, 'Not quite.']], keys: [['બસ', 'ભરાઈ', 'એક જ']] },
    ] },
  { id: 'ba-call', title: 'Phone call with Ba', gu: 'બા સાથે ફોન', who: 'ba', lvl: 1, where: 'On the phone to India', goal: 'Greet Ba, answer her questions, and say goodbye respectfully.',
    turns: [
      { npc: ['હલો? કોણ બોલે છે?', 'halo? koṇ bole chhe?', 'Hello? Who’s speaking?'] },
      { you: 'Greet Ba and say it’s you.', o: [['જય શ્રી કૃષ્ણ બા, હું બોલું છું!', 'jay shrī krishṇa bā, huṁ boluṁ chhuṁ!', 'Jay Shri Krishna Ba, it’s me!', true, '“It’s me speaking” — exactly how you’d say it.'], ['તું કોણ છે?', 'tuṁ koṇ chhe?', 'Who are you?', false, 'Rude — and you’re the one who called her!']], keys: [['જય', 'નમસ્તે', 'હું']] },
      { npc: ['અરે, જય શ્રી કૃષ્ણ બેટા! કેમ છે?', 'are, jay shrī krishṇa beṭā! kem chhe?', 'Oh, Jay Shri Krishna dear! How are you?'] },
      { you: 'Say you’re well, and ask how she is.', o: [['મજામાં, બા. તમે કેમ છો?', 'majāmāṁ, bā. tame kem chho?', 'Fine, Ba. How are you?', true, 'Respectful તમે … છો.'], ['મજામાં. તું કેમ છે?', 'majāmāṁ. tuṁ kem chhe?', 'Fine. How are you (close form)?', false, 'Ba uses તું with you — but you use તમે with her.']], keys: [['મજામાં', 'સારું', 'મસ્ત'], ['તમે', 'કેમ']] },
      { npc: ['હું પણ મજામાં. જમી લીધું?', 'huṁ paṇ majāmāṁ. jamī līdhuṁ?', 'I’m fine too. Have you eaten?'] },
      { you: 'Say yes, you’ve eaten.', o: [['હા બા, જમી લીધું.', 'hā bā, jamī līdhuṁ.', 'Yes Ba, I’ve eaten.', true, 'Dropping the subject is most natural.'], ['હા, હું જમી લીધું.', 'hā, huṁ jamī līdhuṁ.', '(wrong “I”)', false, 'With લીધું, use મેં — or drop it.']], keys: [['જમી', 'જમ્યો', 'જમી લીધું', 'ખાધું', 'હા']] },
      { npc: ['શું ખાધું?', 'shuṁ khādhuṁ?', 'What did you eat?'] },
      { you: 'Tell her: dal-rice and shaak.', o: [['દાળ-ભાત ને શાક.', 'dāḷ-bhāt ne shāk.', 'Dal-rice and shaak.', true, 'Short answers are natural.'], ['હું દાળ છું.', 'huṁ dāḷ chhuṁ.', 'I am dal.', false, 'Not quite!']], keys: [['દાળ', 'ભાત', 'શાક', 'રોટલી', 'પિઝા', 'ખીચડી']] },
      { npc: ['સરસ. ક્યારે આવે છે મળવા?', 'saras. kyāre āve chhe maḷvā?', 'Good. When are you coming to see me?'] },
      { you: 'Say you’ll come on Sunday.', o: [['રવિવારે આવીશ, બા.', 'ravivāre āvīsh, bā.', 'I’ll come on Sunday, Ba.', true, 'Future: આવીશ.'], [G('રવિવારે આવ્યો.', 'રવિવારે આવી.'), G('ravivāre āvyo.', 'ravivāre āvī.'), 'Came on Sunday.', false, 'That’s past tense.']], keys: [['આવીશ', 'આવું']] },
      { npc: ['સારું, ધ્યાન રાખજે. આવજે!', 'sāruṁ, dhyān rākhje. āvje!', 'Okay, take care. Bye!'] },
      { you: 'Say goodbye respectfully.', o: [['જય શ્રી કૃષ્ણ, બા. આવજો!', 'jay shrī krishṇa, bā. āvjo!', 'Jay Shri Krishna, Ba. Bye!', true, 'Respectful આવજો.'], ['આવજે, બા!', 'āvje, bā!', 'Bye (close form), Ba!', false, 'આવજે is what Ba says to you. To her, say આવજો.']], keys: [['આવજો', 'જય']] },
    ] },
  { id: 'sibling', title: 'Where’s my charger?', gu: 'ભાઈ સાથે', who: 'bhai', lvl: 1, where: 'The living room', goal: 'Deny, defend yourself, and tease back — sibling style.',
    turns: [
      { npc: ['એય, મારું ચાર્જર ક્યાં છે?', 'ey, māruṁ chārjar kyāṁ chhe?', 'Hey, where’s my charger?'] },
      { you: 'Say you don’t know.', o: [['મને ખબર નથી.', 'mane khabar nathī.', 'I don’t know.', true, 'Classic.'], ['શું ખબર!', 'shuṁ khabar!', 'Who knows!', true, 'Casual — perfect with a sibling.']], keys: [['ખબર']] },
      { npc: ['તેં લીધું હતું ને?', 'teṁ līdhuṁ hatuṁ ne?', 'You took it, didn’t you?'] },
      { you: 'Say no, you didn’t take it.', o: [['ના, મેં નથી લીધું.', 'nā, meṁ nathī līdhuṁ.', 'No, I didn’t take it.', true, 'Past with an object → મેં.'], ['ના, હું નથી લીધું.', 'nā, huṁ nathī līdhuṁ.', '(wrong “I”)', false, 'With લીધું use મેં.']], keys: [['ના', 'નથી']] },
      { npc: ['તો ક્યાં ગયું? જરા શોધ ને.', 'to kyāṁ gayuṁ? jarā shodh ne.', 'Then where did it go? Help me look.'] },
      { you: 'Tell him to wait, you’re coming.', o: [['ઊભો રહે, આવું છું.', 'ūbho rahe, āvuṁ chhuṁ.', 'Wait, I’m coming.', true, 'ઊભો રહે to a brother.'], ['ઊભા રહો, દાદા.', 'ūbhā raho, dādā.', 'Please wait, Dada.', false, 'You’re talking to your brother.']], keys: [['આવું', 'ઊભો', 'મિનિટ']] },
      { npc: ['મળી ગયું! સોફા નીચે હતું.', 'maḷī gayuṁ! sofā nīche hatuṁ.', 'Found it! It was under the sofa.'] },
      { you: 'Say: “See? I told you!”', o: [['જોયું? મેં કીધું હતું ને!', 'joyuṁ? meṁ kīdhuṁ hatuṁ ne!', 'See? I told you!', true, 'કીધું is the spoken form of કહ્યું (said).'], ['સરસ, આવજો.', 'saras, āvjo.', 'Nice, goodbye.', false, 'Too formal for a sibling win.']], keys: [['જોયું', 'કીધું', 'કહ્યું']] },
    ] },
  { id: 'restaurant', title: 'At a Gujarati restaurant', gu: 'થાળી', who: 'waiter', lvl: 2, where: 'A thali restaurant', goal: 'Order a thali and chaas, compliment the food, ask for the bill.',
    turns: [
      { npc: ['આવો, શું લેશો?', 'āvo, shuṁ lesho?', 'Welcome, what will you have?'] },
      { you: 'Order one Gujarati thali.', o: [['એક ગુજરાતી થાળી આપો.', 'ek gujarātī thāḷī āpo.', 'One Gujarati thali, please.', true, 'Clear and polite.'], ['થાળી ક્યાં છે?', 'thāḷī kyāṁ chhe?', 'Where is the thali?', false, 'You need to order it first.']], keys: [['થાળી']] },
      { npc: ['બીજું કંઈ? છાશ?', 'bījuṁ kaṁī? chhāsh?', 'Anything else? Buttermilk?'] },
      { you: 'Say yes, a chaas too.', o: [['હા, એક છાશ પણ.', 'hā, ek chhāsh paṇ.', 'Yes, a chaas too.', true, 'પણ = too.'], ['ના, બસ.', 'nā, bas.', 'No, that’s all.', true, 'Also fine.']], keys: [['છાશ', 'હા', 'ના', 'બસ']] },
      { npc: ['સારું. દસ મિનિટમાં આવે છે.', 'sāruṁ. das miniṭmāṁ āve chhe.', 'Okay. It’ll come in ten minutes.'] },
      { you: '(Later) Tell him the food is excellent.', o: [['જમવાનું બહુ સરસ છે!', 'jamvānuṁ bahu saras chhe!', 'The food is excellent!', true, 'He’ll bring more without asking.'], ['જમવાનું સરસ છો.', 'jamvānuṁ saras chho.', '(wrong verb)', false, 'Food is છે, not છો.']], keys: [['સરસ', 'મસ્ત', 'સારું']] },
      { npc: ['આભાર! બીજું કંઈ લાવું?', 'ābhār! bījuṁ kaṁī lāvuṁ?', 'Thanks! Shall I bring anything else?'] },
      { you: 'Say no, and ask for the bill.', o: [['ના, બસ. બિલ લાવજો.', 'nā, bas. bil lāvjo.', 'No, that’s all. Please bring the bill.', true, 'Polite -જો form.'], ['બિલ આપો ને.', 'bil āpo ne.', 'The bill, please.', true, 'Also natural.']], keys: [['બિલ']] },
    ] },
  { id: 'market', title: 'Shaak market', gu: 'શાકમાર્કેટ', who: 'shop', lvl: 2, where: 'A vegetable stall', goal: 'Ask the price, bargain, and get free coriander.',
    turns: [
      { you: 'Ask the price of tomatoes.', o: [['ટામેટાં કેમ આપ્યાં?', 'ṭāmeṭāṁ kem āpyāṁ?', 'What’s the rate for tomatoes?', true, 'Market idiom: literally “how did you give them?”.'], ['ટામેટાં કેટલાનાં છે?', 'ṭāmeṭāṁ keṭlānāṁ chhe?', 'How much are the tomatoes?', true, 'Also correct.'], ['ટામેટાં ક્યાં છે?', 'ṭāmeṭāṁ kyāṁ chhe?', 'Where are the tomatoes?', false, 'They’re in front of you.']], keys: [['ટામેટાં', 'ભાવ', 'કેટલા', 'કેમ']] },
      { npc: ['ચાલીસ રૂપિયે કિલો.', 'chālīs rūpiye kilo.', 'Forty rupees a kilo.'] },
      { you: 'Say it’s too expensive — make it thirty.', o: [['બહુ મોંઘાં છે, ત્રીસ કરો ને.', 'bahu moṁghāṁ chhe, trīs karo ne.', 'Too expensive, make it thirty.', true, 'Plural -આં to match ટામેટાં.'], ['બહુ સસ્તાં છે!', 'bahu sastāṁ chhe!', 'They’re very cheap!', false, 'Now he’ll raise the price.']], keys: [['મોંઘ', 'ઓછું', 'ત્રીસ']] },
      { npc: ['ના ના, પાંત્રીસ છેલ્લા.', 'nā nā, pāṁtrīs chhellā.', 'No no, thirty-five, final.'] },
      { you: 'Agree and ask for two kilos.', o: [['સારું, બે કિલો આપો.', 'sāruṁ, be kilo āpo.', 'Okay, give me two kilos.', true, 'Deal.']], keys: [['કિલો', 'આપો', 'સારું']] },
      { npc: ['લો. સિત્તેર રૂપિયા થયા.', 'lo. sitter rūpiyā thayā.', 'Here. That’s seventy rupees.'] },
      { you: 'Ask him to throw in some coriander.', o: [['થોડી કોથમીર નાખી દો ને!', 'thoḍī kothmīr nākhī do ne!', 'Throw in a little coriander, would you!', true, 'Every Gujarati mother’s final move.'], ['કોથમીર મોંઘી છે.', 'kothmīr moṁghī chhe.', 'Coriander is expensive.', false, 'That doesn’t ask for anything.']], keys: [['કોથમીર', 'મરચાં', 'નાખી']] },
      { npc: ['હા, લો! આવજો.', 'hā, lo! āvjo.', 'Sure, here! Bye.'] },
    ] },
  { id: 'directions', title: 'Finding the mandir', gu: 'રસ્તો પૂછવો', who: 'stranger', lvl: 2, where: 'A busy street in Ahmedabad', goal: 'Ask the way, confirm it, and thank them.',
    turns: [
      { you: 'Ask where the Swaminarayan mandir is.', o: [['માફ કરજો, સ્વામિનારાયણ મંદિર ક્યાં છે?', 'māf karjo, svāminārāyaṇ mandir kyāṁ chhe?', 'Excuse me, where’s the Swaminarayan mandir?', true, 'Polite opener + question.'], ['મંદિર કોણ છે?', 'mandir koṇ chhe?', 'Who is the mandir?', false, 'Use ક્યાં (where).']], keys: [['મંદિર'], ['ક્યાં']] },
      { npc: ['સીધા જાઓ, બીજા ચાર રસ્તે ડાબી બાજુ વળજો.', 'sīdhā jāo, bījā chār raste ḍābī bāju vaḷjo.', 'Go straight, and turn left at the second crossroads.'] },
      { you: 'Check: second crossroads, then left?', o: [['બીજા ચાર રસ્તે, ડાબી બાજુ?', 'bījā chār raste, ḍābī bāju?', 'Second crossroads, left?', true, 'Repeating back is smart.'], ['પહેલા ચાર રસ્તે, જમણી બાજુ?', 'pahelā chār raste, jamṇī bāju?', 'First crossroads, right?', false, 'He said the second, and left.']], keys: [['ડાબી'], ['બીજા', 'ચાર રસ્તે']] },
      { npc: ['હા, ત્યાંથી બે મિનિટ.', 'hā, tyāṁthī be miniṭ.', 'Yes, two minutes from there.'] },
      { you: 'Thank them warmly.', o: [['ખૂબ ખૂબ આભાર!', 'khūb khūb ābhār!', 'Thank you so much!', true, 'Doubling = extra warmth.']], keys: [['આભાર', 'થેંક્યુ']] },
    ] },
  { id: 'mandir', title: 'Aunty at the mandir', gu: 'મંદિરમાં મુલાકાત', who: 'aunty', lvl: 2, where: 'After aarti', goal: 'Answer the famous “whose child are you?” and chat politely.',
    turns: [
      { npc: [G('જય શ્રી કૃષ્ણ! તું કોનો દીકરો છે?', 'જય શ્રી કૃષ્ણ! તું કોની દીકરી છે?'), G('jay shrī krishṇa! tuṁ kono dīkro chhe?', 'jay shrī krishṇa! tuṁ konī dīkrī chhe?'), 'Jay Shri Krishna! Whose child are you?'] },
      { you: 'Say you’re Meenaben’s child.', o: [[G('હું મીનાબેનનો દીકરો છું.', 'હું મીનાબેનની દીકરી છું.'), G('huṁ mīnābenno dīkro chhuṁ.', 'huṁ mīnābennī dīkrī chhuṁ.'), 'I’m Meenaben’s son/daughter.', true, 'Families are identified by the parent — add -બેન / -ભાઈ for respect.'], ['હું મીનાબેન છું.', 'huṁ mīnāben chhuṁ.', 'I am Meenaben.', false, 'That makes you your mother!']], keys: [['દીકરો', 'દીકરી', 'નો', 'ની']] },
      { npc: [G('અરે હા! કેટલો મોટો થઈ ગયો!', 'અરે હા! કેટલી મોટી થઈ ગઈ!'), G('are hā! keṭlo moṭo thaī gayo!', 'are hā! keṭlī moṭī thaī gaī!'), 'Oh yes! Look how big you’ve grown!'] },
      { you: 'Smile, and ask how she is.', o: [['હા! તમે કેમ છો, માસી?', 'hā! tame kem chho, māsī?', 'Yes! How are you, Masi?', true, 'Family-friend aunties are often called માસી.'], ['હા, હું મોટો છું.', 'hā, huṁ moṭo chhuṁ.', 'Yes, I am big.', false, 'Technically true. Socially odd.']], keys: [['કેમ', 'મજામાં']] },
      { npc: ['મજામાં. શું કરે છે આજકાલ?', 'majāmāṁ. shuṁ kare chhe ājkāl?', 'Fine. What are you up to these days?'] },
      { you: 'Say you’re studying / working.', o: [['હું કૉલેજમાં ભણું છું.', 'huṁ kolejmāṁ bhaṇuṁ chhuṁ.', 'I’m studying in college.', true, 'Good.'], ['હું નોકરી કરું છું.', 'huṁ nokrī karuṁ chhuṁ.', 'I’m working.', true, 'Good.']], keys: [['ભણું', 'નોકરી', 'કામ']] },
      { npc: ['સરસ! ચાલ, પ્રસાદ લઈ લે.', 'saras! chāl, prasād laī le.', 'Great! Come, take some prasad.'] },
      { you: 'Thank her and say goodbye.', o: [['આભાર, માસી. જય શ્રી કૃષ્ણ!', 'ābhār, māsī. jay shrī krishṇa!', 'Thanks, Masi. Jay Shri Krishna!', true, 'Lovely.']], keys: [['આભાર', 'જય']] },
    ] },
  { id: 'masi', title: 'Visiting Masi', gu: 'માસીને ઘરે', who: 'masi', lvl: 2, where: 'Masi’s living room', goal: 'Handle the classic relative visit: tea, family news, and the “eat before you go”.',
    turns: [
      { npc: [G('આવ આવ! કેટલા વખતે આવ્યો!', 'આવ આવ! કેટલા વખતે આવી!'), G('āv āv! keṭlā vakhte āvyo!', 'āv āv! keṭlā vakhte āvī!'), 'Come in! It’s been so long!'] },
      { you: 'Agree it’s been a long time.', o: [['હા માસી, ઘણા વખતે.', 'hā māsī, ghaṇā vakhte.', 'Yes Masi, it’s been a while.', true, 'Natural echo.']], keys: [['વખતે', 'હા']] },
      { npc: ['ચા પીશે કે કૉફી?', 'chā pīshe ke kofī?', 'Will you have tea or coffee?'] },
      { you: 'Say tea, but just a little.', o: [['ચા, પણ થોડી જ.', 'chā, paṇ thoḍī ja.', 'Tea, but just a little.', true, 'થોડી (feminine) to match ચા.'], ['ચા, થોડો.', 'chā, thoḍo.', '(wrong ending)', false, 'ચા is feminine → થોડી.']], keys: [['ચા', 'કૉફી']] },
      { npc: ['ઘરે બધા કેમ છે?', 'ghare badhā kem chhe?', 'How is everyone at home?'] },
      { you: 'Say everyone is well.', o: [['બધા મજામાં છે.', 'badhā majāmāṁ chhe.', 'Everyone is well.', true, 'Perfect.'], ['બધા મજામાં છું.', 'badhā majāmāṁ chhuṁ.', '(wrong verb)', false, 'બધા (everyone) takes છે.']], keys: [['મજામાં', 'સારું', 'બરાબર']] },
      { npc: [G('જમીને જજે, હોં!', 'જમીને જજે, હોં!'), 'jamīne jaje, hoṁ!', 'Eat before you go, okay!'] },
      { you: 'Accept, or politely decline for today.', o: [['સારું, જમીને જઈશ.', 'sāruṁ, jamīne jaīsh.', 'Okay, I’ll eat before going.', true, 'The easy path.'], ['ના માસી, આજે નહીં. ફરી ક્યારેક.', 'nā māsī, āje nahīṁ. farī kyārek.', 'Not today, Masi. Some other time.', true, 'Polite — expect her to ask twice more.']], keys: [['જમીને', 'નહીં', 'ક્યારેક', 'સારું']] },
    ] },
  { id: 'plans', title: 'Weekend plans', gu: 'શનિવારનો પ્લાન', who: 'cousin', lvl: 3, where: 'Texting your cousin', goal: 'Make a garba plan and fix a time.',
    turns: [
      { npc: ['શનિવારે શું કરે છે?', 'shanivāre shuṁ kare chhe?', 'What are you doing Saturday?'] },
      { you: 'Say nothing much — why?', o: [['કંઈ નહીં, કેમ?', 'kaṁī nahīṁ, kem?', 'Nothing, why?', true, 'Perfectly casual.']], keys: [['કંઈ નહીં', 'કેમ']] },
      { npc: ['ગરબા રમવા જઈએ?', 'garbā ramvā jaīe?', 'Shall we go play garba?'] },
      { you: 'Say yes, and ask when to meet.', o: [['હા, ચાલો! ક્યારે મળીએ?', 'hā, chālo! kyāre maḷīe?', 'Yes, let’s! When do we meet?', true, 'Great.'], ['હા, અમે જઈશું.', 'hā, ame jaīshuṁ.', 'Yes, we (not you) will go.', false, 'અમે leaves your cousin out — use આપણે.']], keys: [['હા', 'ચાલો', 'ચલ'], ['ક્યારે', 'મળીએ']] },
      { npc: ['સાંજે સાત વાગ્યે, મારા ઘરે.', 'sāṁje sāt vāgye, mārā ghare.', 'Seven in the evening, at my place.'] },
      { you: 'Confirm you’ll come at seven.', o: [['સારું, હું સાત વાગ્યે આવીશ.', 'sāruṁ, huṁ sāt vāgye āvīsh.', 'Okay, I’ll come at seven.', true, 'Future: આવીશ.']], keys: [['આવીશ', 'સાત']] },
      { npc: [G('કુર્તો પહેરજે, હોં!', 'ચણિયાચોળી પહેરજે, હોં!'), G('kurto paherje, hoṁ!', 'chaṇiyācholī paherje, hoṁ!'), G('Wear a kurta, okay!', 'Wear a chaniya choli, okay!')] },
      { you: 'Say “Of course!”', o: [['હાસ્તો!', 'hāsto!', 'Of course!', true, 'Casual and confident.'], ['હા, ચોક્કસ.', 'hā, chokkas.', 'Yes, definitely.', true, 'ચોક્કસ = certainly.']], keys: [['હાસ્તો', 'ચોક્કસ', 'હા']] },
    ] },
  { id: 'pappa-day', title: 'How was your day?', gu: 'દિવસ કેવો ગયો?', who: 'pappa', lvl: 3, where: 'Evening at home', goal: 'Talk about your day in the past tense.',
    turns: [
      { npc: ['આજે દિવસ કેવો ગયો?', 'āje divas kevo gayo?', 'How did today go?'] },
      { you: 'Say it went well, lots of work.', o: [['સારો ગયો. બહુ કામ હતું.', 'sāro gayo. bahu kām hatuṁ.', 'It went well. Lots of work.', true, 'દિવસ is masculine → સારો ગયો.'], ['સારું ગયું.', 'sāruṁ gayuṁ.', 'It went well (neuter).', false, 'દિવસ is masculine: સારો ગયો.']], keys: [['સારો', 'સરસ', 'કામ']] },
      { npc: ['શું શું કર્યું?', 'shuṁ shuṁ karyuṁ?', 'What all did you do?'] },
      { you: 'Say: classes in the morning, then lunch with friends.', o: [[G('સવારે ક્લાસ હતા, પછી મિત્રો સાથે જમ્યો.', 'સવારે ક્લાસ હતા, પછી મિત્રો સાથે જમી.'), G('savāre klās hatā, pachhī mitro sāthe jamyo.', 'savāre klās hatā, pachhī mitro sāthe jamī.'), 'Classes in the morning, then ate with friends.', true, 'Nice sequence with પછી.']], keys: [['સવારે', 'પછી', 'ક્લાસ', 'કામ', 'મિત્રો']] },
      { npc: [G('થાકી ગયો હોઈશ.', 'થાકી ગઈ હોઈશ.'), G('thākī gayo hoīsh.', 'thākī gaī hoīsh.'), 'You must be tired.'] },
      { you: 'Say: yes, a little.', o: [[G('હા, થોડો.', 'હા, થોડી.'), G('hā, thoḍo.', 'hā, thoḍī.'), 'Yes, a little.', true, 'Agrees with you.']], keys: [['હા', 'થોડો', 'થોડી']] },
      { npc: ['સારું, આરામ કર.', 'sāruṁ, ārām kar.', 'Okay, get some rest.'] },
      { you: 'Say good night.', o: [['હા પપ્પા. ગુડ નાઇટ!', 'hā pappā. guḍ nāiṭ!', 'Yes Pappa. Good night!', true, 'Gujlish is how most families say it.']], keys: [['નાઇટ', 'હા']] },
    ] },
  { id: 'dada-studies', title: 'Dada asks about studies', gu: 'દાદા સાથે', who: 'dada', lvl: 3, where: 'Dada’s armchair', goal: 'Talk about your studies and receive a blessing.',
    turns: [
      { npc: ['ભણવાનું કેવું ચાલે છે?', 'bhaṇvānuṁ kevuṁ chāle chhe?', 'How are your studies going?'] },
      { you: 'Say they’re going well.', o: [['સરસ ચાલે છે, દાદા.', 'saras chāle chhe, dādā.', 'Going well, Dada.', true, 'Natural.']], keys: [['સરસ', 'સારું', 'ચાલે']] },
      { npc: ['કયો વિષય સૌથી વધારે ગમે છે?', 'kayo viṣhay sauthī vadhāre game chhe?', 'Which subject do you like most?'] },
      { you: 'Say you like maths the most.', o: [['મને ગણિત સૌથી વધારે ગમે છે.', 'mane gaṇit sauthī vadhāre game chhe.', 'I like maths the most.', true, 'Great use of સૌથી વધારે.'], ['હું ગણિત ગમે છું.', 'huṁ gaṇit game chhuṁ.', '(wrong subject)', false, 'Liking uses મને: મને ગણિત ગમે છે.']], keys: [['ગમે']] },
      { npc: ['શાબાશ! મહેનત કરજે.', 'shābāsh! mahenat karje.', 'Well done! Keep working hard.'] },
      { you: 'Ask for his blessing.', o: [['હા દાદા, આશીર્વાદ આપો.', 'hā dādā, āshīrvād āpo.', 'Yes Dada, give me your blessing.', true, 'Dada will melt.']], keys: [['આશીર્વાદ']] },
    ] },
];

/* Gujarati script course. Letters: [glyph, sound, example gu, example tr, example en] */
const SCRIPT = [
  { id: 'v1', title: 'First vowels', gu: 'અ આ ઇ ઈ ઉ ઊ', kind: 'vowel',
    intro: 'Gujarati vowels come in short/long pairs. There’s no line across the top of the letters (unlike Hindi) — Gujarati is the “free-standing” cousin.',
    letters: [['અ', 'a (as in “about”)', 'અમે', 'ame', 'we'], ['આ', 'ā (as in “father”)', 'આભાર', 'ābhār', 'thanks'], ['ઇ', 'i (short, “sit”)', 'ઇનામ', 'inām', 'prize'], ['ઈ', 'ī (long, “see”)', 'ઈશ્વર', 'īshvar', 'God'], ['ઉ', 'u (short, “put”)', 'ઉનાળો', 'unāḷo', 'summer'], ['ઊ', 'ū (long, “food”)', 'ઊન', 'ūn', 'wool']] },
  { id: 'v2', title: 'More vowels', gu: 'એ ઐ ઓ ઔ અં', kind: 'vowel',
    intro: 'એ and ઓ are everywhere. ઐ and ઔ are rarer. The dot (ં) adds a nasal hum.',
    letters: [['એ', 'e (as in “they”)', 'એક', 'ek', 'one'], ['ઐ', 'ai (as in “ai-sle”)', 'ઐતિહાસિક', 'aitihāsik', 'historic'], ['ઓ', 'o (as in “go”)', 'ઓરડો', 'orḍo', 'room'], ['ઔ', 'au (as in “out”)', 'ઔષધ', 'auṣhadh', 'medicine'], ['અં', 'aṁ (nasal)', 'અંદર', 'andar', 'inside'], ['ઋ', 'ru', 'ઋતુ', 'rutu', 'season']] },
  { id: 'c1', title: 'Throat & palate', gu: 'ક ખ ગ ઘ · ચ છ જ ઝ', kind: 'consonant',
    intro: 'Consonants come in families of four: plain, breathy, voiced, voiced-breathy. Every consonant carries a built-in “a”: ક = ka.',
    letters: [['ક', 'ka', 'કમળ', 'kamaḷ', 'lotus'], ['ખ', 'kha (breathy)', 'ખુરશી', 'khurshī', 'chair'], ['ગ', 'ga', 'ગરમ', 'garam', 'hot'], ['ઘ', 'gha (breathy)', 'ઘર', 'ghar', 'house'], ['ચ', 'cha', 'ચા', 'chā', 'tea'], ['છ', 'chha (breathy)', 'છત્રી', 'chhatrī', 'umbrella'], ['જ', 'ja', 'જમવું', 'jamvuṁ', 'to eat a meal'], ['ઝ', 'jha', 'ઝાડ', 'jhāḍ', 'tree']] },
  { id: 'c2', title: 'Curled-back sounds', gu: 'ટ ઠ ડ ઢ ણ', kind: 'consonant',
    intro: 'Curl the tip of your tongue back to the roof of your mouth. These sound “harder” than English t and d.',
    letters: [['ટ', 'ṭa', 'ટામેટું', 'ṭāmeṭuṁ', 'tomato'], ['ઠ', 'ṭha (breathy)', 'ઠંડું', 'ṭhaṇḍuṁ', 'cold'], ['ડ', 'ḍa', 'ડબ્બો', 'ḍabbo', 'tin, box'], ['ઢ', 'ḍha (breathy)', 'ઢોકળા', 'ḍhoklā', 'dhokla'], ['ણ', 'ṇa', 'ત્રણ', 'traṇ', 'three']] },
  { id: 'c3', title: 'Teeth sounds', gu: 'ત થ દ ધ ન', kind: 'consonant',
    intro: 'Tongue touches the back of your top teeth. Softer than English t and d. થ is NOT the English “th”.',
    letters: [['ત', 'ta (soft)', 'તમે', 'tame', 'you'], ['થ', 'tha (breathy)', 'થાળી', 'thāḷī', 'plate, thali'], ['દ', 'da (soft)', 'દૂધ', 'dūdh', 'milk'], ['ધ', 'dha (breathy)', 'ધન્યવાદ', 'dhanyavād', 'thank you (formal)'], ['ન', 'na', 'નમસ્તે', 'namaste', 'hello']] },
  { id: 'c4', title: 'Lip sounds', gu: 'પ ફ બ ભ મ', kind: 'consonant',
    intro: 'Made with your lips. Most Gujaratis pronounce ફ as “f”.',
    letters: [['પ', 'pa', 'પાણી', 'pāṇī', 'water'], ['ફ', 'fa / pha', 'ફૂલ', 'fūl', 'flower'], ['બ', 'ba', 'બા', 'bā', 'grandma'], ['ભ', 'bha (breathy)', 'ભાઈ', 'bhāī', 'brother'], ['મ', 'ma', 'મમ્મી', 'mammī', 'mom']] },
  { id: 'c5', title: 'The rest', gu: 'ય ર લ વ શ ષ સ હ ળ', kind: 'consonant',
    intro: 'Semi-vowels, hissing sounds, and Gujarati’s special curled-back ળ.',
    letters: [['ય', 'ya', 'યાદ', 'yād', 'memory'], ['ર', 'ra', 'રોટલી', 'roṭlī', 'rotli'], ['લ', 'la', 'લીંબુ', 'līmbu', 'lemon'], ['વ', 'va (between v and w)', 'વરસાદ', 'varsād', 'rain'], ['શ', 'sha', 'શાક', 'shāk', 'shaak'], ['ષ', 'sha (formal words)', 'ભાષા', 'bhāṣhā', 'language'], ['સ', 'sa', 'સાત', 'sāt', 'seven'], ['હ', 'ha', 'હાથ', 'hāth', 'hand'], ['ળ', 'ḷa (curled back)', 'દાળ', 'dāḷ', 'dal']] },
  { id: 'm1', title: 'Vowel signs I', gu: 'કા કિ કી', kind: 'matra',
    intro: 'After a consonant, vowels turn into small signs (માત્રા) attached to it. ક + ા = કા. Note: િ is written BEFORE the letter but said after it.',
    letters: [['ા', 'ā  (કા kā)', 'કામ', 'kām', 'work'], ['િ', 'i  (કિ ki)', 'દિવસ', 'divas', 'day'], ['ી', 'ī  (કી kī)', 'દીકરી', 'dīkrī', 'daughter']] },
  { id: 'm2', title: 'Vowel signs II', gu: 'કુ કૂ કે કૈ કો કૌ કં', kind: 'matra',
    intro: 'The rest of the vowel signs. With these you can read almost any Gujarati word.',
    letters: [['ુ', 'u  (કુ ku)', 'ગુજરાતી', 'gujarātī', 'Gujarati'], ['ૂ', 'ū  (કૂ kū)', 'દૂધ', 'dūdh', 'milk'], ['ે', 'e  (કે ke)', 'બે', 'be', 'two'], ['ૈ', 'ai  (કૈ kai)', 'પૈસા', 'paisā', 'money'], ['ો', 'o  (કો ko)', 'મોર', 'mor', 'peacock'], ['ૌ', 'au  (કૌ kau)', 'સૌથી', 'sauthī', 'most'], ['ં', 'nasal  (કં kaṁ)', 'હું', 'huṁ', 'I']] },
  { id: 'j1', title: 'Joined letters', gu: 'સ્ત ત્ર ક્ય', kind: 'conjunct',
    intro: 'When two consonants meet with no vowel between, they join. Often the first loses its right-hand stroke. ્ (virama) shows a consonant with no vowel.',
    letters: [['સ્ત', 's + ta', 'નમસ્તે', 'namaste', 'hello'], ['ત્ર', 't + ra', 'ત્રણ', 'traṇ', 'three'], ['ક્ય', 'k + ya', 'ક્યાં', 'kyāṁ', 'where'], ['પ્ર', 'p + ra', 'પ્રસાદ', 'prasād', 'prasad'], ['ક્ષ', 'kṣha', 'પરીક્ષા', 'parīkṣhā', 'exam'], ['જ્ઞ', 'gna / gya', 'જ્ઞાન', 'gnān', 'knowledge']] },
  { id: 'n1', title: 'Gujarati numerals', gu: '૧ ૨ ૩', kind: 'numeral',
    intro: 'You’ll see these on price tags, calendars and old family documents.',
    letters: [['૧', '1 · એક', '૧', 'ek', 'one'], ['૨', '2 · બે', '૨', 'be', 'two'], ['૩', '3 · ત્રણ', '૩', 'traṇ', 'three'], ['૪', '4 · ચાર', '૪', 'chār', 'four'], ['૫', '5 · પાંચ', '૫', 'pāṁch', 'five'], ['૬', '6 · છ', '૬', 'chha', 'six'], ['૭', '7 · સાત', '૭', 'sāt', 'seven'], ['૮', '8 · આઠ', '૮', 'āṭh', 'eight'], ['૯', '9 · નવ', '૯', 'nav', 'nine'], ['૦', '0 · શૂન્ય', '૦', 'shūnya', 'zero']] },
];

/* Placement test. tier 1..5. type: mcq (show gu/en prompt), listen (play audio), speak. */
const PLACEMENT = [
  { tier: 1, skill: 'vocab', type: 'mcq', prompt: 'નમસ્તે', tr: 'namaste', q: 'What does this mean?', o: ['Hello', 'Thank you', 'Goodbye', 'Sorry'], a: 0 },
  { tier: 1, skill: 'listening', type: 'listen', audio: 'આભાર', q: 'What did you hear?', o: ['Thank you', 'Yes', 'No', 'Hello'], a: 0 },
  { tier: 1, skill: 'reading', type: 'mcq', prompt: 'Which one says “kem chho?”', q: '', o: ['કેમ છો?', 'ક્યાં છો?', 'શું છે?', 'કોણ છો?'], a: 0, noTr: true },
  { tier: 1, skill: 'vocab', type: 'mcq', prompt: 'દાદી', tr: 'dādī', q: 'Who is this?', o: ['Dad’s mother', 'Mom’s sister', 'Dad’s sister', 'Mom’s mother'], a: 0 },
  { tier: 2, skill: 'vocab', type: 'mcq', prompt: 'મને ભૂખ લાગી છે.', q: 'What does this mean?', o: ['I’m hungry.', 'I’m thirsty.', 'I’m tired.', 'I’m happy.'], a: 0 },
  { tier: 2, skill: 'grammar', type: 'mcq', prompt: 'હું ઘરે ___ છું.', q: 'Fill the blank: “I’m going home.”', o: ['જાઉં', 'જાય', 'જાઓ', 'જશે'], a: 0 },
  { tier: 2, skill: 'listening', type: 'listen', audio: 'તમે ક્યાં રહો છો?', q: 'What did you hear?', o: ['Where do you live?', 'What do you do?', 'When will you come?', 'Who are you?'], a: 0 },
  { tier: 2, skill: 'grammar', type: 'mcq', prompt: '“Where are you going?”', q: 'Pick the correct Gujarati.', o: ['તમે ક્યાં જાઓ છો?', 'તમે જાઓ ક્યાં છો છે?', 'ક્યાં તમે છો?', 'તમે શું કરો છો?'], a: 0, noTr: true },
  { tier: 3, skill: 'grammar', type: 'mcq', prompt: '“I ate a rotli.”', q: 'Pick the correct Gujarati.', o: ['મેં રોટલી ખાધી.', 'હું રોટલી ખાધી.', 'મેં રોટલી ખાધો.', 'મને રોટલી ખાધી.'], a: 0, noTr: true },
  { tier: 3, skill: 'grammar', type: 'mcq', prompt: 'કાલે હું આવીશ.', q: 'What does this mean?', o: ['I’ll come tomorrow.', 'I came yesterday.', 'I’m coming now.', 'Come tomorrow.'], a: 0 },
  { tier: 3, skill: 'reading', type: 'mcq', prompt: 'મારાં નાની મુંબઈમાં રહે છે.', q: 'What does this mean? (no transliteration)', o: ['My maternal grandmother lives in Mumbai.', 'My aunt went to Mumbai.', 'My small house is in Mumbai.', 'My grandfather lives in Mumbai.'], a: 0, noTr: true },
  { tier: 4, skill: 'grammar', type: 'mcq', prompt: 'Ba asks: “જમી લીધું?”', q: 'Best reply?', o: ['હા બા, જમી લીધું.', 'હા, હું જમી લીધું.', 'હા, તું જમી?', 'જમવાનું છે.'], a: 0, noTr: true },
  { tier: 4, skill: 'vocab', type: 'mcq', prompt: 'ચા નથી? ચાલશે.', q: 'What does ચાલશે mean here?', o: ['That’s fine / it’ll do', 'Let’s walk', 'It will leave', 'Hurry up'], a: 0, noTr: true },
  { tier: 4, skill: 'grammar', type: 'mcq', prompt: '“This is Dad’s phone.”', q: 'Pick the correct Gujarati.', o: ['આ પપ્પાનો ફોન છે.', 'આ પપ્પાની ફોન છે.', 'આ પપ્પાનું ફોન છે.', 'આ પપ્પા ફોન છે.'], a: 0, noTr: true },
  { tier: 5, skill: 'listening', type: 'listen', audio: 'કંઈક ખાઈ લે, પછી જા. મોડું થાય છે.', q: 'What did you hear?', o: ['Eat something, then go. It’s getting late.', 'Go now, you can eat later.', 'Don’t eat, it’s late.', 'We’ll eat when you come back.'], a: 0 },
  { tier: 5, skill: 'reading', type: 'mcq', prompt: 'ગયા રવિવારે અમે મંદિરે ગયા. અચાનક વરસાદ પડવા લાગ્યો, પણ બહુ મજા આવી.', q: 'What happened? (no transliteration)', o: ['It suddenly rained, but it was fun.', 'The mandir was closed.', 'They stayed home because of rain.', 'They will go next Sunday.'], a: 0, noTr: true },
];

const CHARACTERS = {
  ba:       { name: 'Ba', gu: 'બા', role: 'Grandma', skin: '#C98E5F', hair: '#E9E6E1', style: 'bun', bindi: true, glasses: true, cloth: '#B83A52' },
  dada:     { name: 'Dada', gu: 'દાદા', role: 'Grandpa', skin: '#B97F52', hair: '#EDEBE6', style: 'bald', glasses: true, mustache: true, cloth: '#F1EDE4', topi: true },
  nani:     { name: 'Nani', gu: 'નાની', role: 'Mom’s mother', skin: '#D4A075', hair: '#D9D6D0', style: 'bun', bindi: true, cloth: '#2E8B7A' },
  mummy:    { name: 'Mummy', gu: 'મમ્મી', role: 'Mom', skin: '#D6A27A', hair: '#2A1C17', style: 'bun', bindi: true, cloth: '#E3A21A' },
  pappa:    { name: 'Pappa', gu: 'પપ્પા', role: 'Dad', skin: '#C08A5F', hair: '#221814', style: 'short', mustache: true, glasses: true, cloth: '#3A4DA8' },
  bhai:     { name: 'Bhai', gu: 'ભાઈ', role: 'Brother', skin: '#CB9368', hair: '#1D1411', style: 'spiky', cloth: '#0F9B8E' },
  masi:     { name: 'Masi', gu: 'માસી', role: 'Mom’s sister', skin: '#D8A57C', hair: '#2B1D18', style: 'long', bindi: true, cloth: '#C2417B' },
  aunty:    { name: 'Aunty', gu: 'આન્ટી', role: 'Family friend', skin: '#C7916A', hair: '#3A2A22', style: 'bun', bindi: true, glasses: true, cloth: '#7B4FB5' },
  uncle:    { name: 'Uncle', gu: 'અંકલ', role: 'Family friend', skin: '#B98459', hair: '#5A4A40', style: 'short', mustache: true, cloth: '#E8E2D6' },
  friend:   { name: 'Priya', gu: 'પ્રિયા', role: 'New friend', skin: '#D9AA84', hair: '#231815', style: 'long', cloth: '#F07A3A' },
  cousin:   { name: 'Kinjal', gu: 'કિંજલ', role: 'Cousin', skin: '#CF9A70', hair: '#1E1512', style: 'pony', cloth: '#E24A6A' },
  shop:     { name: 'Rameshbhai', gu: 'રમેશભાઈ', role: 'Shopkeeper', skin: '#A9744B', hair: '#2E221C', style: 'short', mustache: true, cloth: '#E6D9B8' },
  waiter:   { name: 'Waiter', gu: 'વેઇટર', role: 'Restaurant', skin: '#B7825A', hair: '#1C1410', style: 'short', cloth: '#2B2F8F' },
  stranger: { name: 'Passer-by', gu: 'રાહદારી', role: 'Stranger', skin: '#C48C60', hair: '#3B2B22', style: 'short', cloth: '#6B7A8F' },
};

const ACHIEVEMENTS = [
  { id: 'first', title: 'પહેલો પાઠ', en: 'First lesson', desc: 'Finish your first lesson.' },
  { id: 'spoke10', title: 'બોલતા થયા', en: 'Found your voice', desc: 'Speak 10 lines out loud.' },
  { id: 'spoke100', title: 'વાતોડિયા', en: 'Chatterbox', desc: 'Speak 100 lines out loud.' },
  { id: 'streak3', title: 'ત્રણ દીવા', en: 'Three diyas', desc: 'Keep a 3-day streak.' },
  { id: 'streak7', title: 'અઠવાડિયું', en: 'A full week', desc: 'Keep a 7-day streak.' },
  { id: 'words50', title: 'પચાસ શબ્દો', en: '50 words', desc: 'Have 50 words at Familiar or better.' },
  { id: 'convo1', title: 'પહેલી વાતચીત', en: 'First conversation', desc: 'Finish a conversation.' },
  { id: 'baCall', title: 'બાનો ફોન', en: 'Called Ba', desc: 'Finish the phone call with Ba.' },
  { id: 'script1', title: 'અક્ષર', en: 'Letters', desc: 'Finish a script unit.' },
  { id: 'fixer', title: 'ભૂલ સુધારી', en: 'Mistake fixer', desc: 'Fix 10 past mistakes in review.' },
  { id: 'level2', title: 'રોજનું ગુજરાતી', en: 'Everyday speaker', desc: 'Reach Level 2.' },
  { id: 'home10', title: 'ઘરનું ગુજરાતી', en: 'Home speaker', desc: 'Practice 10 Home Gujarati phrases.' },
];
