/* Bolo — Gujarati course content.
   Transliteration scheme (used everywhere):
   ā ī ū = long vowels · ṭ ṭh ḍ ḍh ṇ ḷ = retroflex (tongue curled back) · t th d dh n = dental (tongue on teeth)
   ṁ = nasal hum (anusvara / chandrabindu) · ch = ચ · chh = છ (with a puff of air) · sh = શ/ષ · f = ફ
   G(m, f) marks a line that changes with the speaker's gender (હું ગયો / હું ગઈ). */

const G = (m, f) => ({ m, f });
const w = (gu, tr, en, say, note, extra) => Object.assign({ gu, tr, en, say, note }, extra || {});
const s = (gu, tr, en, note, extra) => Object.assign({ gu, tr, en, note }, extra || {});

const COURSE = [
/* ───────────────────────── LEVEL 1 ───────────────────────── */
{ n: 1, key: 'foundations', title: 'Foundations', gu: 'પાયો', tr: 'pāyo',
  blurb: 'Greetings, family, numbers and your first real sentences.',
  units: [
  { id: '1a', title: 'Say hello', gu: 'નમસ્તે', lessons: [
    { id: 'L01', title: 'First hellos', gu: 'પહેલી વાત', mins: 6,
      can: 'Greet someone, ask how they are, and say goodbye.',
      words: [
        w('નમસ્તે', 'namaste', 'hello', 'nuh-muss-TAY', 'Works with anyone at any time of day. Join your palms for elders.'),
        w('કેમ છો?', 'kem chho?', 'how are you?', 'kem CHHO — push a little air out on chh', 'The respectful form. To a close friend or sibling: કેમ છે?'),
        w('મજામાં', 'majāmāṁ', 'doing well', 'muh-JAA-maaṁ — end with a light nasal hum', 'Literally “in joy”. The standard reply to કેમ છો?'),
        w('આભાર', 'ābhār', 'thank you', 'AA-bhaar — the bh has a puff of air', 'Correct everywhere. At home, family often skips thanks — a smile does the job.'),
        w('આવજો', 'āvjo', 'goodbye', 'AAV-jo', 'Literally “please come (again)”. Said to someone who is leaving, or when you leave.'),
      ],
      sents: [
        s('તમે કેમ છો?', 'tame kem chho?', 'How are you?'),
        s('હું મજામાં છું.', 'huṁ majāmāṁ chhuṁ.', 'I’m doing well.'),
        s('મજામાં, આભાર.', 'majāmāṁ, ābhār.', 'Fine, thanks.'),
        s('સારું, આવજો!', 'sāruṁ, āvjo!', 'Okay, bye!'),
      ],
      grammar: { kind: 'sound', title: 'Sound spotlight: છ (chh)',
        body: 'Gujarati has pairs of sounds that English speakers hear as the same. ચ (ch) is plain. છ (chh) has a puff of air after it — hold your hand in front of your mouth and you should feel it.',
        examples: [['ચા', 'chā', 'tea (plain ch)'], ['છો', 'chho', 'are (puff of air)'], ['છે', 'chhe', 'is (puff of air)']],
        tip: 'કેમ છો? always has the puff. Without it, it sounds lazy to a native ear.' },
      talk: { who: 'masi', ctx: 'Your Masi (mom’s sister) greets you at the door.', gu: 'અરે, કેમ છો?', tr: 'are, kem chho?', en: 'Oh hey, how are you?',
        o: [['મજામાં, આભાર.', 'majāmāṁ, ābhār.', 'Fine, thanks.', true, 'The natural reply.'],
            ['આવજો!', 'āvjo!', 'Bye!', false, 'That’s goodbye — she just said hello.'],
            ['આભાર, કેમ છો.', 'ābhār, kem chho.', 'Thanks, how are you.', false, 'Answer her question first: મજામાં.']] } },

    { id: 'L02', title: 'Yes, no & okay', gu: 'હા, ના', mins: 6,
      can: 'Say yes, no, okay, and excuse me.',
      words: [
        w('હા', 'hā', 'yes', 'haa'),
        w('ના', 'nā', 'no', 'naa', 'Also used in “ના, આભાર” — no, thanks.'),
        w('સારું', 'sāruṁ', 'good / okay', 'SAA-ruṁ — soft nasal at the end', 'Used exactly like “okay” to close a topic: સારું, આવજો.'),
        w('બરાબર', 'barābar', 'right, correct', 'buh-RAA-bur', 'Also “okay, got it”. બરાબર? = “All good?”'),
        w('માફ કરજો', 'māf karjo', 'sorry / excuse me', 'MAAF kur-jo', 'Polite and respectful. Use it with strangers and elders.'),
      ],
      sents: [
        s('હા, બરાબર.', 'hā, barābar.', 'Yes, that’s right.'),
        s('ના, આભાર.', 'nā, ābhār.', 'No, thanks.'),
        s('સારું છે.', 'sāruṁ chhe.', 'It’s good.'),
        s('માફ કરજો, મને મોડું થઈ ગયું.', 'māf karjo, mane moḍuṁ thaī gayuṁ.', 'Sorry, I’m late.', 'Gujarati says “lateness happened to me” — no gender needed.'),
      ],
      grammar: { kind: 'sound', title: 'Sound spotlight: the nasal ં',
        body: 'The dot on top (ં) makes the vowel nasal — let a little air through your nose, like the end of the French “bon”. It is often at the end of a word.',
        examples: [['સારું', 'sāruṁ', 'good / okay'], ['હું', 'huṁ', 'I'], ['શું', 'shuṁ', 'what']],
        tip: 'Don’t pronounce a full “m” or “n”. It’s a hum, not a letter.' },
      talk: { who: 'mummy', ctx: 'Mummy is making chai.', gu: 'ચા પીવી છે?', tr: 'chā pīvī chhe?', en: 'Want some tea?',
        o: [['હા, આભાર.', 'hā, ābhār.', 'Yes, thanks.', true, 'Perfect.'],
            ['ના, આભાર.', 'nā, ābhār.', 'No, thanks.', true, 'Polite and natural.'],
            ['આવજો.', 'āvjo.', 'Bye.', false, 'That’s goodbye — answer with હા or ના.']] } },

    { id: 'L03', title: 'Talking to elders', gu: 'વડીલો સાથે', mins: 7,
      can: 'Greet grandparents respectfully and choose between તું and તમે.',
      words: [
        w('જય શ્રી કૃષ્ણ', 'jay shrī krishṇa', 'hello (respectful greeting)', 'jay shree KRISH-na — many Gujaratis say “krush-na”', 'The everyday greeting in many Gujarati homes. Some families say જય સ્વામિનારાયણ instead — use what your family uses.'),
        w('તમે', 'tame', 'you (respectful)', 'TUH-may', 'For elders, strangers, anyone you respect — and for more than one person.'),
        w('તું', 'tuṁ', 'you (close)', 'tuṁ — short u, light nasal', 'For siblings, friends, children. Using it with an elder sounds rude.'),
        w('બા', 'bā', 'grandma', 'baa', 'In many families બા is grandmother; in some it means mother. Your family decides.'),
        w('દાદા', 'dādā', 'grandpa (dad’s father)', 'DAA-daa'),
      ],
      sents: [
        s('જય શ્રી કૃષ્ણ, બા!', 'jay shrī krishṇa, bā!', 'Jay Shri Krishna, Ba!'),
        s('દાદા, તમે કેમ છો?', 'dādā, tame kem chho?', 'Dada, how are you?'),
        s('તું કેમ છે?', 'tuṁ kem chhe?', 'How are you? (to a friend or sibling)'),
        s('બા મજામાં છે.', 'bā majāmāṁ chhe.', 'Ba is doing well.'),
      ],
      grammar: { kind: 'grammar', title: 'Two ways to say “you”',
        body: 'Gujarati has a respectful “you” and a close “you”, and the verb changes with it. Getting this right matters more to elders than perfect grammar.',
        table: [['તમે', 'tame', 'elders, strangers, respect', 'તમે કેમ છો?'], ['તું', 'tuṁ', 'siblings, friends, kids', 'તું કેમ છે?']],
        tip: 'When in doubt, use તમે. Nobody is offended by too much respect.',
        drills: [
          { t: 'fill', gu: 'દાદા, ___ કેમ છો?', tr: 'dādā, ___ kem chho?', en: 'Dada, how are you?', a: 'તમે', o: ['તમે', 'તું'], why: 'Dada is an elder, and છો goes with તમે.', tag: 'respect' },
          { t: 'pick', q: 'Your little brother walks in. You ask:', o: ['તું કેમ છે?', 'તમે કેમ છો?'], a: 0, why: 'With a younger sibling, તું is natural. તમે would sound oddly formal.', tag: 'respect' },
        ] },
      talk: { who: 'dada', ctx: 'Dada calls you over.', gu: 'જય શ્રી કૃષ્ણ, બેટા!', tr: 'jay shrī krishṇa, beṭā!', en: 'Jay Shri Krishna, dear!',
        o: [['જય શ્રી કૃષ્ણ, દાદા! તમે કેમ છો?', 'jay shrī krishṇa, dādā! tame kem chho?', 'Jay Shri Krishna, Dada! How are you?', true, 'Warm and respectful.'],
            ['તું કેમ છે, દાદા?', 'tuṁ kem chhe, dādā?', 'How are you (close form), Dada?', false, 'તું with a grandparent sounds disrespectful. Use તમે … છો.'],
            ['આવજો, દાદા.', 'āvjo, dādā.', 'Bye, Dada.', false, 'He’s greeting you, not leaving.']] } },
  ]},
  { id: '1b', title: 'Family', gu: 'પરિવાર', lessons: [
    { id: 'L04', title: 'My family', gu: 'મારો પરિવાર', mins: 7,
      can: 'Introduce your parents and siblings.',
      words: [
        w('મમ્મી', 'mammī', 'mom', 'MUM-mee', 'Also મા or બા in some families.'),
        w('પપ્પા', 'pappā', 'dad', 'PUP-paa', 'Also બાપુજી or ભાઈ in some families.'),
        w('ભાઈ', 'bhāī', 'brother', 'BHAA-ee — puff of air on bh', 'Also added to men’s names as respect: રમેશભાઈ.'),
        w('બહેન', 'bahen', 'sister', 'said like “ben”', 'Casually written બેન. Added to women’s names too: મીનાબેન.'),
        w('આ', 'ā', 'this', 'aa', 'Also “he / she” for someone right here.'),
      ],
      sents: [
        s('આ મારો ભાઈ છે.', 'ā māro bhāī chhe.', 'This is my brother.'),
        s('આ મારી બહેન છે.', 'ā mārī bahen chhe.', 'This is my sister.'),
        s('આ મારા પપ્પા છે.', 'ā mārā pappā chhe.', 'This is my dad.'),
        s('આ મારાં મમ્મી છે.', 'ā mārāṁ mammī chhe.', 'This is my mom.', 'Respectful plural for a parent. Casually you’ll also hear મારી મમ્મી.'),
      ],
      grammar: { kind: 'grammar', title: '“My” changes to match',
        body: 'Gujarati nouns are masculine, feminine or neuter, and “my” changes its ending to match the person or thing — not you.',
        table: [['મારો', 'māro', 'masculine', 'મારો ભાઈ'], ['મારી', 'mārī', 'feminine', 'મારી બહેન'], ['મારું', 'māruṁ', 'neuter', 'મારું ઘર'], ['મારા / મારાં', 'mārā / mārāṁ', 'respect (elders)', 'મારા પપ્પા, મારાં મમ્મી']],
        tip: 'Ending in -ો = he-word, -ી = she-word, -ું = it-word. You’ll see this pattern everywhere.',
        drills: [
          { t: 'fill', gu: 'આ ___ બહેન છે.', tr: 'ā ___ bahen chhe.', en: 'This is my sister.', a: 'મારી', o: ['મારો', 'મારી', 'મારું'], why: 'બહેન is feminine, so “my” is મારી.', tag: 'agreement' },
          { t: 'fill', gu: 'આ ___ ભાઈ છે.', tr: 'ā ___ bhāī chhe.', en: 'This is my brother.', a: 'મારો', o: ['મારો', 'મારી', 'મારું'], why: 'ભાઈ is masculine, so “my” is મારો.', tag: 'agreement' },
        ] },
      talk: { who: 'aunty', ctx: 'An aunty points at your brother.', gu: 'આ કોણ છે?', tr: 'ā koṇ chhe?', en: 'Who is this?',
        o: [['આ મારો ભાઈ છે.', 'ā māro bhāī chhe.', 'This is my brother.', true, 'Exactly right.'],
            ['આ મારી ભાઈ છે.', 'ā mārī bhāī chhe.', '(wrong ending)', false, 'ભાઈ is masculine → મારો ભાઈ.'],
            ['હું ભાઈ છું.', 'huṁ bhāī chhuṁ.', 'I am brother.', false, 'She asked who *he* is.']] } },

    { id: 'L05', title: 'Grandparents & uncles', gu: 'દાદી, નાના, મામા', mins: 7,
      can: 'Name relatives on your mom’s side and your dad’s side.',
      words: [
        w('દાદી', 'dādī', 'grandma (dad’s mother)', 'DAA-dee'),
        w('નાના', 'nānā', 'grandpa (mom’s father)', 'NAA-naa'),
        w('નાની', 'nānī', 'grandma (mom’s mother)', 'NAA-nee', 'Careful: નાની also means “small” (feminine).'),
        w('કાકા', 'kākā', 'uncle (dad’s brother)', 'KAA-kaa'),
        w('મામા', 'māmā', 'uncle (mom’s brother)', 'MAA-maa'),
      ],
      sents: [
        s('આ મારા કાકા છે.', 'ā mārā kākā chhe.', 'This is my (paternal) uncle.'),
        s('દાદી ઘરે છે.', 'dādī ghare chhe.', 'Grandma is at home.'),
        s('મારાં નાની મુંબઈમાં રહે છે.', 'mārāṁ nānī mumbaīmāṁ rahe chhe.', 'My (maternal) grandma lives in Mumbai.'),
        s('મામા અને નાના આવે છે.', 'māmā ane nānā āve chhe.', 'Mama and Nana are coming.'),
      ],
      grammar: { kind: 'culture', title: 'Whose side of the family?',
        body: 'English says “uncle” and “grandma”. Gujarati always tells you which side of the family someone is on — and families use these words as names.',
        table: [['Dad’s side', '', 'દાદા · દાદી · કાકા · કાકી · ફોઈ', ''], ['Mom’s side', '', 'નાના · નાની · મામા · મામી · માસી', '']],
        tip: 'Close family friends are often called કાકા / માસી too, even when they aren’t related.' },
      talk: { who: 'ba', ctx: 'Ba shows you a photo of your mom’s brother.', gu: 'આ કોણ છે, ઓળખે છે?', tr: 'ā koṇ chhe, oḷkhe chhe?', en: 'Who’s this, do you recognize him?',
        o: [['આ મારા મામા છે.', 'ā mārā māmā chhe.', 'This is my Mama.', true, 'Right — mom’s brother is મામા.'],
            ['આ મારા કાકા છે.', 'ā mārā kākā chhe.', 'This is my Kaka.', false, 'કાકા is dad’s brother. Mom’s brother is મામા.'],
            ['આ મારી મામા છે.', 'ā mārī māmā chhe.', '(wrong ending)', false, 'For an elder man: મારા મામા.']] } },

    { id: 'L06', title: 'Aunts, sons & daughters', gu: 'માસી, ફોઈ', mins: 7,
      can: 'Talk about aunts and children.',
      words: [
        w('માસી', 'māsī', 'aunt (mom’s sister)', 'MAA-see'),
        w('ફોઈ', 'foī', 'aunt (dad’s sister)', 'FO-ee'),
        w('કાકી', 'kākī', 'aunt (Kaka’s wife)', 'KAA-kee'),
        w('દીકરો', 'dīkro', 'son', 'DEEK-ro'),
        w('દીકરી', 'dīkrī', 'daughter', 'DEEK-ree'),
      ],
      sents: [
        s('મારાં માસી અમેરિકામાં રહે છે.', 'mārāṁ māsī amerikāmāṁ rahe chhe.', 'My Masi lives in America.'),
        s('ફોઈ અને કાકી ઘરે છે.', 'foī ane kākī ghare chhe.', 'Foi and Kaki are at home.'),
        s('આ મારી દીકરી છે.', 'ā mārī dīkrī chhe.', 'This is my daughter.'),
        s('એમનો દીકરો ડૉક્ટર છે.', 'emno dīkro ḍokṭar chhe.', 'Their son is a doctor.'),
      ],
      talk: { who: 'masi', ctx: 'Your mom’s sister is on the phone.', gu: 'હલો, ઓળખ્યું?', tr: 'halo, oḷkhyuṁ?', en: 'Hello, recognize me?',
        o: [['હા, જય શ્રી કૃષ્ણ, માસી!', 'hā, jay shrī krishṇa, māsī!', 'Yes, Jay Shri Krishna, Masi!', true, 'Mom’s sister = માસી.'],
            ['હા, જય શ્રી કૃષ્ણ, ફોઈ!', 'hā, jay shrī krishṇa, foī!', 'Yes, … Foi!', false, 'ફોઈ is dad’s sister.'],
            ['હા, જય શ્રી કૃષ્ણ, કાકી!', 'hā, jay shrī krishṇa, kākī!', 'Yes, … Kaki!', false, 'કાકી is Kaka’s wife.']] } },
  ]},
  { id: '1c', title: 'Numbers & things', gu: 'આંકડા', lessons: [
    { id: 'L07', title: 'Numbers 1–5', gu: 'એક થી પાંચ', mins: 6,
      can: 'Count to five and ask for a number of things.',
      words: [
        w('એક', 'ek', 'one · ૧', 'ayk'),
        w('બે', 'be', 'two · ૨', 'bay'),
        w('ત્રણ', 'traṇ', 'three · ૩', 'truhṇ — curl the tongue back for ṇ'),
        w('ચાર', 'chār', 'four · ૪', 'chaar'),
        w('પાંચ', 'pāṁch', 'five · ૫', 'paaṁch — nasal aa'),
      ],
      sents: [
        s('બે ચા આપો.', 'be chā āpo.', 'Two teas, please.'),
        s('મારે ત્રણ ભાઈ છે.', 'māre traṇ bhāī chhe.', 'I have three brothers.', 'Gujarati “have” for family: મારે … છે (to me … is).'),
        s('એક મિનિટ!', 'ek miniṭ!', 'One minute!'),
        s('પાંચ વાગ્યા છે.', 'pāṁch vāgyā chhe.', 'It’s five o’clock.'),
      ],
      grammar: { kind: 'sound', title: 'Sound spotlight: ણ (ṇ)',
        body: 'ણ is an “n” said with the tongue curled back to the roof of the mouth. It never starts a word, but it ends many.',
        examples: [['ત્રણ', 'traṇ', 'three'], ['પાણી', 'pāṇī', 'water'], ['કોણ', 'koṇ', 'who']],
        tip: 'Gujarati numerals: ૧ ૨ ૩ ૪ ૫ — you’ll see them on prices and calendars.' },
      talk: { who: 'mummy', ctx: 'Mummy is serving dinner.', gu: 'કેટલી રોટલી જોઈએ?', tr: 'keṭlī roṭlī joīe?', en: 'How many rotlis do you want?',
        o: [['બે રોટલી આપો.', 'be roṭlī āpo.', 'Give me two rotlis.', true, 'Clear and polite.'],
            ['બે, બસ.', 'be, bas.', 'Two, that’s it.', true, 'Very natural at the table.'],
            ['બે ભાઈ.', 'be bhāī.', 'Two brothers.', false, 'She asked about rotli!']] } },

    { id: 'L08', title: 'Numbers 6–10', gu: 'છ થી દસ', mins: 6,
      can: 'Count to ten and tell the time on the hour.',
      words: [
        w('છ', 'chha', 'six · ૬', 'chhuh — puff of air'),
        w('સાત', 'sāt', 'seven · ૭', 'saat — soft dental t'),
        w('આઠ', 'āṭh', 'eight · ૮', 'aaṭh — curled-back ṭ with air'),
        w('નવ', 'nav', 'nine · ૯', 'nuv', 'Also means “new” in formal words, but everyday “new” is નવું.'),
        w('દસ', 'das', 'ten · ૧૦', 'duss — soft dental d'),
      ],
      sents: [
        s('સાત વાગ્યા છે.', 'sāt vāgyā chhe.', 'It’s seven o’clock.'),
        s('હું દસ મિનિટમાં આવું છું.', 'huṁ das miniṭmāṁ āvuṁ chhuṁ.', 'I’ll be there in ten minutes.'),
        s('નવ વાગ્યે મળીએ.', 'nav vāgye maḷīe.', 'Let’s meet at nine.'),
        s('કેટલા વાગ્યા?', 'keṭlā vāgyā?', 'What time is it?'),
      ],
      grammar: { kind: 'sound', title: 'Sound spotlight: two kinds of t and d',
        body: 'ત and દ are said with the tongue touching your teeth (softer than English). ટ and ડ are said with the tongue curled back (harder than English). English t/d sits in between, so Gujarati ears hear it as ટ/ડ.',
        examples: [['સાત', 'sāt', 'seven (soft, dental)'], ['આઠ', 'āṭh', 'eight (curled back)'], ['દસ', 'das', 'ten (soft, dental)']],
        tip: 'For સાત, touch the back of your top teeth. For આઠ, curl the tip of your tongue up and back.' },
      talk: { who: 'pappa', ctx: 'Pappa is looking for his watch.', gu: 'કેટલા વાગ્યા?', tr: 'keṭlā vāgyā?', en: 'What time is it?',
        o: [['આઠ વાગ્યા છે.', 'āṭh vāgyā chhe.', 'It’s eight o’clock.', true, 'Perfect.'],
            ['નવ વાગ્યે.', 'nav vāgye.', 'At nine.', false, 'વાગ્યે = “at … o’clock”. He asked what time it is: વાગ્યા છે.'],
            ['આઠ રોટલી.', 'āṭh roṭlī.', 'Eight rotlis.', false, 'That answers a different question.']] } },

    { id: 'L09', title: 'Things around you', gu: 'વસ્તુઓ', mins: 7,
      can: 'Ask for everyday things politely.',
      words: [
        w('પાણી', 'pāṇī', 'water', 'PAA-ṇee'),
        w('ચા', 'chā', 'tea (chai)', 'chaa', 'Feminine: ગરમ ચા, ઠંડી ચા.'),
        w('ફોન', 'fon', 'phone', 'fone', 'Masculine: મારો ફોન.'),
        w('ચાવી', 'chāvī', 'key', 'CHAA-vee'),
        w('ચોપડી', 'chopḍī', 'book', 'CHOP-ḍee', 'Also પુસ્તક (pustak), more formal.'),
      ],
      sents: [
        s('પાણી આપો.', 'pāṇī āpo.', 'Please give (me) water.'),
        s('મારો ફોન ક્યાં છે?', 'māro fon kyāṁ chhe?', 'Where is my phone?'),
        s('આ તમારી ચા.', 'ā tamārī chā.', 'Here’s your tea.'),
        s('ચાવી આપ ને.', 'chāvī āp ne.', 'Give me the key, would you?', 'ને at the end softens a request, like “would you?”'),
      ],
      grammar: { kind: 'grammar', title: 'Asking for things',
        body: '“Give” is આપવું. To an elder or stranger say આપો. To a sibling or friend say આપ. Add ને at the end to make it friendly.',
        table: [['આપો', 'āpo', 'respectful', 'દાદી, પાણી આપો ને.'], ['આપ', 'āp', 'close', 'ભાઈ, ચાવી આપ ને.']],
        tip: 'Many families use તું with Mummy but તમે with Pappa and grandparents. Follow what you hear at home.',
        drills: [
          { t: 'pick', q: 'Ask Dadi for water:', o: ['દાદી, પાણી આપો ને.', 'દાદી, પાણી આપ.'], a: 0, why: 'Dadi is an elder: use આપો.', tag: 'respect' },
          { t: 'fill', gu: 'ભાઈ, ચાવી ___ ને.', tr: 'bhāī, chāvī ___ ne.', en: 'Bhai, give me the key, would you?', a: 'આપ', o: ['આપ', 'આપો'], why: 'To a brother, the close form આપ is natural.', tag: 'respect' },
        ] },
      talk: { who: 'bhai', ctx: 'Your brother is by the door.', gu: 'શું જોઈએ?', tr: 'shuṁ joīe?', en: 'What do you need?',
        o: [['ચાવી આપ ને.', 'chāvī āp ne.', 'Give me the key, would you?', true, 'Natural between siblings.'],
            ['ચાવી આપો, દાદા.', 'chāvī āpo, dādā.', 'Give the key, Dada.', false, 'You’re talking to your brother, not Dada.'],
            ['મારી ચાવી છું.', 'mārī chāvī chhuṁ.', 'I am my key.', false, 'છું means “am”.']] } },
  ]},
  { id: '1d', title: 'First sentences', gu: 'પહેલાં વાક્યો', lessons: [
    { id: 'L10', title: 'Question words', gu: 'શું? ક્યાં? કોણ?', mins: 7,
      can: 'Ask what, where, who, when and why.',
      words: [
        w('શું', 'shuṁ', 'what', 'shuṁ — light nasal'),
        w('ક્યાં', 'kyāṁ', 'where', 'kyaaṁ — nasal aa'),
        w('કોણ', 'koṇ', 'who', 'koṇ — curled-back ṇ'),
        w('ક્યારે', 'kyāre', 'when', 'KYAA-ray'),
        w('કેમ', 'kem', 'why / how', 'kem', 'કેમ છો? = how are you? · કેમ? on its own = why?'),
      ],
      sents: [
        s('આ શું છે?', 'ā shuṁ chhe?', 'What is this?'),
        s('મમ્મી ક્યાં છે?', 'mammī kyāṁ chhe?', 'Where is Mummy?'),
        s('એ કોણ છે?', 'e koṇ chhe?', 'Who is that?'),
        s('પપ્પા ક્યારે આવશે?', 'pappā kyāre āvshe?', 'When will Dad come?'),
      ],
      grammar: { kind: 'grammar', title: 'Question words sit before the verb',
        body: 'English puts “where” first. Gujarati usually keeps the sentence in normal order and drops the question word in just before the verb.',
        examples: [['મમ્મી ક્યાં છે?', 'mammī kyāṁ chhe?', 'Mummy where is? → Where is Mummy?'], ['તમે શું કરો છો?', 'tame shuṁ karo chho?', 'You what do? → What do you do?']],
        tip: 'Yes/no questions need no question word at all — just raise your voice at the end: ચા પીવી છે?',
        drills: [
          { t: 'fill', gu: 'મારો ફોન ___ છે?', tr: 'māro fon ___ chhe?', en: 'Where is my phone?', a: 'ક્યાં', o: ['ક્યાં', 'કોણ', 'શું'], why: 'ક્યાં = where.', tag: 'vocabulary' },
          { t: 'fill', gu: 'એ ___ છે?', tr: 'e ___ chhe?', en: 'Who is that?', a: 'કોણ', o: ['ક્યારે', 'કોણ', 'ક્યાં'], why: 'કોણ = who.', tag: 'vocabulary' },
        ] },
      talk: { who: 'mummy', ctx: 'You’re searching the couch.', gu: 'શું શોધે છે?', tr: 'shuṁ shodhe chhe?', en: 'What are you looking for?',
        o: [['મારો ફોન ક્યાં છે?', 'māro fon kyāṁ chhe?', 'Where is my phone?', true, 'Natural answer by asking.'],
            ['ફોન કોણ છે?', 'fon koṇ chhe?', 'Who is the phone?', false, 'કોણ = who. Use ક્યાં (where).'],
            ['હા, ફોન.', 'hā, fon.', 'Yes, phone.', false, 'Her question wasn’t yes/no.']] } },

    { id: 'L11', title: 'I am, you are', gu: 'છું, છે, છો', mins: 8,
      can: 'Say where people are, and where they aren’t.',
      words: [
        w('હું', 'huṁ', 'I', 'huṁ'),
        w('છું', 'chhuṁ', 'am', 'chhuṁ — puff of air + nasal'),
        w('છે', 'chhe', 'is', 'chhay'),
        w('છો', 'chho', 'are (with તમે)', 'chho'),
        w('નથી', 'nathī', 'am not / is not / are not', 'NUH-thee', 'One word covers every person: હું નથી, તમે નથી, એ નથી.'),
      ],
      sents: [
        s('હું ઘરે છું.', 'huṁ ghare chhuṁ.', 'I’m at home.'),
        s('તમે ક્યાં છો?', 'tame kyāṁ chho?', 'Where are you?'),
        s('પપ્પા ઘરે નથી.', 'pappā ghare nathī.', 'Dad isn’t home.'),
        s('હું તૈયાર છું.', 'huṁ taiyār chhuṁ.', 'I’m ready.'),
      ],
      grammar: { kind: 'grammar', title: '“To be” in Gujarati',
        body: 'The verb goes at the end, and changes with the person. “Not” is simply નથી, for everyone.',
        table: [['હું', 'huṁ', 'I', 'છું'], ['તું', 'tuṁ', 'you (close)', 'છે'], ['એ', 'e', 'he / she / it', 'છે'], ['અમે / આપણે', 'ame / āpaṇe', 'we', 'છીએ'], ['તમે', 'tame', 'you (respect)', 'છો'], ['તેઓ', 'teo', 'they', 'છે']],
        tip: 'છે does the most work: it’s “is”, “you are” (close) and “they are”.',
        drills: [
          { t: 'fill', gu: 'હું ઘરે ___.', tr: 'huṁ ghare ___.', en: 'I am at home.', a: 'છું', o: ['છું', 'છે', 'છો'], why: 'હું always pairs with છું.', tag: 'verb-ending' },
          { t: 'fill', gu: 'તમે ક્યાં ___?', tr: 'tame kyāṁ ___?', en: 'Where are you?', a: 'છો', o: ['છું', 'છે', 'છો'], why: 'તમે pairs with છો.', tag: 'verb-ending' },
          { t: 'fill', gu: 'પપ્પા ઘરે ___.', tr: 'pappā ghare ___.', en: 'Dad isn’t home.', a: 'નથી', o: ['છે', 'નથી', 'છું'], why: 'નથી = is not.', tag: 'negation' },
        ] },
      talk: { who: 'pappa', ctx: 'Pappa calls your phone.', gu: 'તું ક્યાં છે?', tr: 'tuṁ kyāṁ chhe?', en: 'Where are you?',
        o: [['હું ઘરે છું.', 'huṁ ghare chhuṁ.', 'I’m at home.', true, 'Correct.'],
            ['હું ઘરે છે.', 'huṁ ghare chhe.', '(wrong ending)', false, 'હું takes છું, not છે.'],
            ['તમે ઘરે છો.', 'tame ghare chho.', 'You are at home.', false, 'He asked where *you* are.']] } },

    { id: 'L12', title: 'Introduce yourself', gu: 'મારું નામ', mins: 8,
      can: 'Say your name and that you speak a little Gujarati.',
      words: [
        w('નામ', 'nām', 'name', 'naam'),
        w('મારું', 'māruṁ', 'my (neuter)', 'MAA-ruṁ', 'નામ is neuter, so it’s મારું નામ.'),
        w('તમારું', 'tamāruṁ', 'your (respectful, neuter)', 'tuh-MAA-ruṁ'),
        w('ગુજરાતી', 'gujarātī', 'Gujarati', 'goo-juh-RAA-tee'),
        w('થોડું', 'thoḍuṁ', 'a little', 'THO-ḍuṁ'),
      ],
      sents: [
        s('તમારું નામ શું છે?', 'tamāruṁ nām shuṁ chhe?', 'What is your name?'),
        s('મારું નામ નીલ છે.', 'māruṁ nām nīl chhe.', 'My name is Neel.'),
        s('મને થોડું ગુજરાતી આવડે છે.', 'mane thoḍuṁ gujarātī āvḍe chhe.', 'I know a little Gujarati.'),
        s('હું ગુજરાતી શીખું છું.', 'huṁ gujarātī shīkhuṁ chhuṁ.', 'I’m learning Gujarati.'),
      ],
      grammar: { kind: 'grammar', title: '“Gujarati comes to me”',
        body: 'For skills you know, Gujarati says the skill “comes to you”: મને ગુજરાતી આવડે છે. મને means “to me”. This “to me” pattern shows up again for liking, needing and feeling.',
        examples: [['મને ગુજરાતી આવડે છે.', 'mane gujarātī āvḍe chhe.', 'I know Gujarati.'], ['તમને ગુજરાતી આવડે છે?', 'tamne gujarātī āvḍe chhe?', 'Do you know Gujarati?'], ['મને થોડું થોડું આવડે છે.', 'mane thoḍuṁ thoḍuṁ āvḍe chhe.', 'I know a little bit.']],
        tip: 'Doubling a word softens or spreads it: થોડું થોડું = “a little bit”, ધીમે ધીમે = “slowly, gradually”.' },
      talk: { who: 'uncle', ctx: 'An uncle at the mandir is surprised you understood him.', gu: 'તમને ગુજરાતી આવડે છે?', tr: 'tamne gujarātī āvḍe chhe?', en: 'You know Gujarati?',
        o: [['હા, થોડું થોડું આવડે છે.', 'hā, thoḍuṁ thoḍuṁ āvḍe chhe.', 'Yes, a little bit.', true, 'Humble and natural — uncles love this answer.'],
            ['હા, મારું નામ ગુજરાતી છે.', 'hā, māruṁ nām gujarātī chhe.', 'Yes, my name is Gujarati.', false, 'That says your name is “Gujarati”.'],
            ['ના, આભાર.', 'nā, ābhār.', 'No, thanks.', false, 'Sounds like you’re declining an offer.']] },
      read: { title: 'Neel introduces himself',
        lines: [['નમસ્તે! મારું નામ નીલ છે.', 'namaste! māruṁ nām nīl chhe.', 'Hello! My name is Neel.'],
                ['હું અમેરિકામાં રહું છું.', 'huṁ amerikāmāṁ rahuṁ chhuṁ.', 'I live in America.'],
                ['મને થોડું ગુજરાતી આવડે છે.', 'mane thoḍuṁ gujarātī āvḍe chhe.', 'I know a little Gujarati.'],
                ['મારાં બા અમદાવાદમાં રહે છે.', 'mārāṁ bā amdāvādmāṁ rahe chhe.', 'My Ba lives in Ahmedabad.']],
        qs: [{ q: 'Where does Neel live?', o: ['America', 'Ahmedabad', 'Mumbai'], a: 0 },
             { q: 'Where does Ba live?', o: ['America', 'Ahmedabad', 'Surat'], a: 1 }] } },
  ]},
]},

/* ───────────────────────── LEVEL 2 ───────────────────────── */
{ n: 2, key: 'everyday', title: 'Everyday Gujarati', gu: 'રોજનું ગુજરાતી', tr: 'rojnuṁ gujarātī',
  blurb: 'Food, home, routines, places, shopping and how you feel.',
  units: [
  { id: '2a', title: 'Food & the kitchen', gu: 'જમવાનું', lessons: [
    { id: 'L13', title: 'Food at home', gu: 'દાળ-ભાત', mins: 7,
      can: 'Name the dishes of a Gujarati thali and ask what’s cooking.',
      words: [
        w('રોટલી', 'roṭlī', 'rotli (thin flatbread)', 'ROṬ-lee'),
        w('દાળ', 'dāḷ', 'dal (lentil soup)', 'daaḷ — curled-back ḷ', 'Gujarati dal is often a little sweet and sour.'),
        w('ભાત', 'bhāt', 'cooked rice', 'bhaat — puff on bh', 'Masculine: થોડો ભાત.'),
        w('શાક', 'shāk', 'shaak (vegetable dish)', 'shaak', 'Neuter: કયું શાક?'),
        w('જમવાનું', 'jamvānuṁ', 'the meal, food', 'jum-VAA-nuṁ'),
      ],
      sents: [
        s('જમવાનું તૈયાર છે.', 'jamvānuṁ taiyār chhe.', 'Food’s ready.'),
        s('આજે કયું શાક છે?', 'āje kayuṁ shāk chhe?', 'Which shaak is it today?'),
        s('દાળ-ભાત બહુ સરસ છે.', 'dāḷ-bhāt bahu saras chhe.', 'The dal-rice is really good.'),
        s('થોડો ભાત આપો.', 'thoḍo bhāt āpo.', 'Give me a little rice, please.'),
      ],
      grammar: { kind: 'sound', title: 'Sound spotlight: ળ (ḷ)',
        body: 'ળ is an “l” with the tongue curled back — the same move as ટ and ણ. Hindi doesn’t have it; Gujarati uses it all the time.',
        examples: [['દાળ', 'dāḷ', 'dal'], ['કમળ', 'kamaḷ', 'lotus'], ['મળીએ', 'maḷīe', 'let’s meet']],
        tip: 'Say “l”, then slide your tongue tip back along the roof of your mouth while still saying it.' },
      talk: { who: 'mummy', ctx: 'Mummy calls from the kitchen.', gu: 'જમવાનું તૈયાર છે!', tr: 'jamvānuṁ taiyār chhe!', en: 'Food’s ready!',
        o: [['આવું છું, મમ્મી!', 'āvuṁ chhuṁ, mammī!', 'Coming, Mummy!', true, 'Exactly what you’d shout back.'],
            ['જમવાનું ક્યાં છે?', 'jamvānuṁ kyāṁ chhe?', 'Where is the food?', false, 'She just told you — it’s ready in the kitchen.'],
            ['આભાર, આવજો.', 'ābhār, āvjo.', 'Thanks, bye.', false, 'You’d be leaving before dinner!']] } },

    { id: 'L14', title: 'Hungry & thirsty', gu: 'ભૂખ લાગી', mins: 8,
      can: 'Say you’re hungry or thirsty, and ask elders if they’ve eaten.',
      words: [
        w('ભૂખ', 'bhūkh', 'hunger', 'bhookh — air on both bh and kh'),
        w('તરસ', 'taras', 'thirst', 'TUH-russ'),
        w('ખાવું', 'khāvuṁ', 'to eat', 'KHAA-vuṁ', 'For eating anything — a snack, fruit, a meal.'),
        w('પીવું', 'pīvuṁ', 'to drink', 'PEE-vuṁ', 'Gujarati “drinks” tea and water — and also cigarettes!'),
        w('જમવું', 'jamvuṁ', 'to have a meal', 'JUM-vuṁ', 'Politer than ખાવું. Ask elders: જમ્યા?'),
      ],
      sents: [
        s('મને ભૂખ લાગી છે.', 'mane bhūkh lāgī chhe.', 'I’m hungry.'),
        s('મને તરસ લાગી છે.', 'mane taras lāgī chhe.', 'I’m thirsty.'),
        s('હું ચા પીઉં છું.', 'huṁ chā pīuṁ chhuṁ.', 'I drink tea.'),
        s('ચાલો, જમી લઈએ.', 'chālo, jamī laīe.', 'Come on, let’s eat.'),
      ],
      grammar: { kind: 'grammar', title: 'Hunger happens to you',
        body: 'Gujarati doesn’t say “I am hungry”. It says “hunger has struck me”: મને ભૂખ લાગી છે. Change મને to talk about someone else.',
        table: [['મને', 'mane', 'to me', 'મને ભૂખ લાગી છે.'], ['તને', 'tane', 'to you (close)', 'તને તરસ લાગી છે?'], ['તમને', 'tamne', 'to you (respect)', 'તમને ભૂખ લાગી છે?']],
        tip: 'Never “હું ભૂખ છું” — that means “I am hunger”.',
        drills: [
          { t: 'fill', gu: '___ ભૂખ લાગી છે.', tr: '___ bhūkh lāgī chhe.', en: 'I’m hungry.', a: 'મને', o: ['મને', 'હું', 'મારું'], why: 'Feelings use મને (to me).', tag: 'dative' },
          { t: 'pick', q: 'Ask Dada if he’s hungry:', o: ['દાદા, તમને ભૂખ લાગી છે?', 'દાદા, તને ભૂખ લાગી છે?'], a: 0, why: 'તમને for an elder.', tag: 'respect' },
        ] },
      talk: { who: 'ba', ctx: 'Ba notices you snacking.', gu: 'ભૂખ લાગી છે?', tr: 'bhūkh lāgī chhe?', en: 'Are you hungry?',
        o: [['હા બા, બહુ ભૂખ લાગી છે!', 'hā bā, bahu bhūkh lāgī chhe!', 'Yes Ba, I’m really hungry!', true, 'Ba will be delighted.'],
            ['હું ભૂખ છું.', 'huṁ bhūkh chhuṁ.', 'I am hunger.', false, 'Say મને ભૂખ લાગી છે — hunger strikes *you*.'],
            ['હા, મને તરસ છે.', 'hā, mane taras chhe.', 'Yes, I have thirst.', false, 'She asked about hunger, and it’s તરસ લાગી છે.']] } },

    { id: 'L15', title: 'Tastes', gu: 'તીખું, મીઠું', mins: 8,
      can: 'Say if food is spicy, sweet, hot or cold.',
      words: [
        w('તીખું', 'tīkhuṁ', 'spicy (hot)', 'TEE-khuṁ'),
        w('મીઠું', 'mīṭhuṁ', 'sweet · also “salt”', 'MEE-ṭhuṁ', 'As a noun, મીઠું is salt: મીઠું આપો = pass the salt.'),
        w('ગરમ', 'garam', 'hot (temperature)', 'GUH-rum', 'Never changes its ending.'),
        w('ઠંડું', 'ṭhaṇḍuṁ', 'cold', 'ṬHUN-ḍuṁ'),
        w('બહુ', 'bahu', 'very, a lot', 'buh-HOO', 'Also ખૂબ (khūb), slightly more formal.'),
      ],
      sents: [
        s('ચા બહુ ગરમ છે.', 'chā bahu garam chhe.', 'The tea is very hot.'),
        s('શાક બહુ તીખું છે.', 'shāk bahu tīkhuṁ chhe.', 'The shaak is very spicy.'),
        s('ઠંડું પાણી આપો.', 'ṭhaṇḍuṁ pāṇī āpo.', 'Give me cold water, please.'),
        s('દાળ થોડી મીઠી છે.', 'dāḷ thoḍī mīṭhī chhe.', 'The dal is a little sweet.'),
      ],
      grammar: { kind: 'grammar', title: 'Adjectives match the noun',
        body: 'Adjectives ending in -ઉં/-ઓ/-ઈ change to match the noun’s gender. Adjectives ending in a consonant (ગરમ, સરસ) never change.',
        table: [['ઠંડો ભાત', 'ṭhaṇḍo bhāt', 'masculine', '-ઓ'], ['ઠંડી ચા', 'ṭhaṇḍī chā', 'feminine', '-ઈ'], ['ઠંડું પાણી', 'ṭhaṇḍuṁ pāṇī', 'neuter', '-ઉં']],
        tip: 'Learn nouns with an adjective attached: “ઠંડી ચા”, not just “ચા”. The gender comes for free.',
        drills: [
          { t: 'fill', gu: 'ચા ___ છે.', tr: 'chā ___ chhe.', en: 'The tea is cold.', a: 'ઠંડી', o: ['ઠંડો', 'ઠંડી', 'ઠંડું'], why: 'ચા is feminine → ઠંડી.', tag: 'agreement' },
          { t: 'fill', gu: 'પાણી ___ છે.', tr: 'pāṇī ___ chhe.', en: 'The water is cold.', a: 'ઠંડું', o: ['ઠંડો', 'ઠંડી', 'ઠંડું'], why: 'પાણી is neuter → ઠંડું.', tag: 'agreement' },
        ] },
      talk: { who: 'pappa', ctx: 'Pappa made the shaak today.', gu: 'શાક કેવું છે?', tr: 'shāk kevuṁ chhe?', en: 'How’s the shaak?',
        o: [['સરસ છે, પણ થોડું તીખું છે.', 'saras chhe, paṇ thoḍuṁ tīkhuṁ chhe.', 'It’s nice, but a little spicy.', true, 'Honest and kind.'],
            ['શાક તીખો છે.', 'shāk tīkho chhe.', '(wrong ending)', false, 'શાક is neuter → તીખું.'],
            ['મને ભૂખ છે.', 'mane bhūkh chhe.', 'I have hunger.', false, 'He asked how it tastes.']] } },
  ]},
  { id: '2b', title: 'Home & routine', gu: 'ઘર અને દિવસ', lessons: [
    { id: 'L16', title: 'Around the house', gu: 'ઘરમાં', mins: 8,
      can: 'Say where people and things are in the house.',
      words: [
        w('ઘર', 'ghar', 'house, home', 'ghur — air on gh'),
        w('રસોડું', 'rasoḍuṁ', 'kitchen', 'ruh-SO-ḍuṁ'),
        w('રૂમ', 'rūm', 'room', 'room', 'Also ઓરડો (orḍo), more traditional.'),
        w('બારણું', 'bārṇuṁ', 'door', 'BAAR-ṇuṁ', 'Also દરવાજો (darvājo).'),
        w('બારી', 'bārī', 'window', 'BAA-ree'),
      ],
      sents: [
        s('મમ્મી રસોડામાં છે.', 'mammī rasoḍāmāṁ chhe.', 'Mummy is in the kitchen.'),
        s('ફોન રૂમમાં છે.', 'fon rūmmāṁ chhe.', 'The phone is in the room.'),
        s('બારણું બંધ કરો.', 'bārṇuṁ bandh karo.', 'Close the door, please.'),
        s('બારી ખોલ ને.', 'bārī khol ne.', 'Open the window, would you?'),
      ],
      grammar: { kind: 'grammar', title: '-માં means “in”',
        body: 'Stick -માં onto the end of a noun to say “in”. Neuter nouns ending in -ઉં change to -આ first: રસોડું → રસોડામાં.',
        examples: [['ઘરમાં', 'gharmāṁ', 'in the house'], ['રૂમમાં', 'rūmmāṁ', 'in the room'], ['રસોડામાં', 'rasoḍāmāṁ', 'in the kitchen']],
        tip: 'ઘરે (at home) is a special short form you’ll hear constantly: હું ઘરે છું.',
        drills: [
          { t: 'fill', gu: 'મમ્મી ___ છે.', tr: 'mammī ___ chhe.', en: 'Mummy is in the kitchen.', a: 'રસોડામાં', o: ['રસોડુંમાં', 'રસોડામાં', 'રસોડું'], why: 'રસોડું → રસોડા + માં.', tag: 'postposition' },
        ] },
      talk: { who: 'pappa', ctx: 'Pappa just got home.', gu: 'મમ્મી ક્યાં છે?', tr: 'mammī kyāṁ chhe?', en: 'Where’s Mummy?',
        o: [['મમ્મી રસોડામાં છે.', 'mammī rasoḍāmāṁ chhe.', 'Mummy is in the kitchen.', true, 'Correct form.'],
            ['મમ્મી રસોડુંમાં છે.', 'mammī rasoḍuṁmāṁ chhe.', '(wrong form)', false, 'રસોડું becomes રસોડા before -માં.'],
            ['મમ્મી રસોડું છે.', 'mammī rasoḍuṁ chhe.', 'Mummy is a kitchen.', false, 'You need -માં (in).']] } },

    { id: 'L17', title: 'Daily routine', gu: 'રોજનું', mins: 9,
      can: 'Say what you do every day, in the present tense.',
      words: [
        w('ઊઠવું', 'ūṭhvuṁ', 'to wake up, get up', 'OOṬH-vuṁ'),
        w('સૂવું', 'sūvuṁ', 'to sleep', 'SOO-vuṁ', 'Going to sleep: સૂઈ જવું.'),
        w('જવું', 'javuṁ', 'to go', 'JUH-vuṁ'),
        w('આવવું', 'āvvuṁ', 'to come', 'AAV-vuṁ'),
        w('કરવું', 'karvuṁ', 'to do', 'KUR-vuṁ'),
      ],
      sents: [
        s('હું સાત વાગ્યે ઊઠું છું.', 'huṁ sāt vāgye ūṭhuṁ chhuṁ.', 'I get up at seven.'),
        s('તમે શું કરો છો?', 'tame shuṁ karo chho?', 'What are you doing? / What do you do?'),
        s('હું ઘરે જાઉં છું.', 'huṁ ghare jāuṁ chhuṁ.', 'I’m going home.'),
        s('બા વહેલાં સૂઈ જાય છે.', 'bā vahelāṁ sūī jāy chhe.', 'Ba goes to sleep early.'),
      ],
      grammar: { kind: 'grammar', title: 'The present tense',
        body: 'Take the verb stem (કર from કરવું), add the ending for the person, then the “to be” word. One form covers both “I do” and “I’m doing”.',
        table: [['હું', 'કરું છું', 'jāuṁ chhuṁ', 'જાઉં છું'], ['તું / એ', 'કરે છે', 'jāy chhe', 'જાય છે'], ['અમે / આપણે', 'કરીએ છીએ', 'jaīe chhīe', 'જઈએ છીએ'], ['તમે', 'કરો છો', 'jāo chho', 'જાઓ છો']],
        tip: 'Listen for the vowel before છ: -ઉં છું (I), -ઓ છો (you, respect), -ે છે (he/she).',
        drills: [
          { t: 'fill', gu: 'હું ઘરે ___ છું.', tr: 'huṁ ghare ___ chhuṁ.', en: 'I’m going home.', a: 'જાઉં', o: ['જાઉં', 'જાય', 'જાઓ'], why: 'હું → જાઉં છું.', tag: 'verb-ending' },
          { t: 'fill', gu: 'તમે શું ___ છો?', tr: 'tame shuṁ ___ chho?', en: 'What are you doing?', a: 'કરો', o: ['કરું', 'કરે', 'કરો'], why: 'તમે → કરો છો.', tag: 'verb-ending' },
        ] },
      talk: { who: 'bhai', ctx: 'Your brother pokes his head in.', gu: 'શું કરે છે?', tr: 'shuṁ kare chhe?', en: 'What are you doing?',
        o: [['કંઈ નહીં, ટીવી જોઉં છું.', 'kaṁī nahīṁ, ṭīvī jouṁ chhuṁ.', 'Nothing, watching TV.', true, 'Very natural.'],
            ['હું શું કરો છો.', 'huṁ shuṁ karo chho.', '(mixed up)', false, 'હું needs -ઉં છું: કરું છું.'],
            ['તમે ટીવી જુઓ છો.', 'tame ṭīvī juo chho.', 'You’re watching TV.', false, 'He asked about you.']] } },

    { id: 'L18', title: 'Time words', gu: 'આજે, કાલે', mins: 7,
      can: 'Talk about today, tomorrow, mornings and evenings.',
      words: [
        w('આજે', 'āje', 'today', 'AA-jay'),
        w('કાલે', 'kāle', 'tomorrow · yesterday', 'KAA-lay', 'The verb’s tense tells you which one!'),
        w('સવારે', 'savāre', 'in the morning', 'suh-VAA-ray'),
        w('સાંજે', 'sāṁje', 'in the evening', 'SAAṁ-jay'),
        w('હમણાં', 'hamṇāṁ', 'now, right now', 'HUM-ṇaaṁ', 'હમણાં જ = just now.'),
      ],
      sents: [
        s('કાલે મળીએ.', 'kāle maḷīe.', 'See you tomorrow.'),
        s('હમણાં આવું છું.', 'hamṇāṁ āvuṁ chhuṁ.', 'I’m coming right now.'),
        s('સાંજે શું કરો છો?', 'sāṁje shuṁ karo chho?', 'What are you doing this evening?'),
        s('આજે બહુ ગરમી છે.', 'āje bahu garmī chhe.', 'It’s very hot today.'),
      ],
      grammar: { kind: 'grammar', title: 'કાલે: tomorrow or yesterday?',
        body: 'કાલે means both. Future verb → tomorrow. Past verb → yesterday. When it matters, people say આવતી કાલે (tomorrow) or ગઈ કાલે (yesterday).',
        examples: [['કાલે હું આવીશ.', 'kāle huṁ āvīsh.', 'I’ll come tomorrow.'], ['કાલે હું આવ્યો.', 'kāle huṁ āvyo.', 'I came yesterday.']],
        drills: [
          { t: 'pick', q: '“કાલે હું આવીશ.” When?', o: ['Tomorrow', 'Yesterday'], a: 0, why: 'આવીશ is future.', tag: 'tense' },
          { t: 'pick', q: '“કાલે અમે મંદિરે ગયા.” When?', o: ['Tomorrow', 'Yesterday'], a: 1, why: 'ગયા is past.', tag: 'tense' },
        ] },
      talk: { who: 'friend', ctx: 'A friend is leaving.', gu: 'કાલે મળીએ?', tr: 'kāle maḷīe?', en: 'Meet tomorrow?',
        o: [['હા, સાંજે મળીએ.', 'hā, sāṁje maḷīe.', 'Yes, let’s meet in the evening.', true, 'Natural.'],
            ['હા, સવારે મળીએ.', 'hā, savāre maḷīe.', 'Yes, let’s meet in the morning.', true, 'Natural.'],
            ['હું કાલે છું.', 'huṁ kāle chhuṁ.', 'I am tomorrow.', false, 'That doesn’t mean anything.']] } },
  ]},
  { id: '2c', title: 'Out & about', gu: 'બહાર', lessons: [
    { id: 'L19', title: 'Places', gu: 'મંદિર, દુકાન', mins: 8,
      can: 'Say where you’re going.',
      words: [
        w('મંદિર', 'mandir', 'temple, mandir', 'MUN-dir'),
        w('દુકાન', 'dukān', 'shop', 'doo-KAAN'),
        w('સ્કૂલ', 'skūl', 'school', 'skool', 'Also શાળા (shāḷā), the Gujarati word.'),
        w('બજાર', 'bajār', 'market', 'buh-JAAR'),
        w('ઑફિસ', 'ofis', 'office', 'OF-is'),
      ],
      sents: [
        s('હું દુકાને જાઉં છું.', 'huṁ dukāne jāuṁ chhuṁ.', 'I’m going to the shop.'),
        s('ચાલો, મંદિરે જઈએ.', 'chālo, mandire jaīe.', 'Come on, let’s go to the mandir.'),
        s('પપ્પા ઑફિસે ગયા છે.', 'pappā ofise gayā chhe.', 'Dad has gone to the office.'),
        s('બજાર ક્યાં છે?', 'bajār kyāṁ chhe?', 'Where’s the market?'),
      ],
      grammar: { kind: 'grammar', title: 'Going “to” a place: -એ',
        body: 'Add -એ to a place to mean “to” or “at”: દુકાને, મંદિરે, ઘરે. English words often skip it: સ્કૂલ જાઉં છું is fine.',
        examples: [['દુકાને', 'dukāne', 'to/at the shop'], ['મંદિરે', 'mandire', 'to/at the mandir'], ['ઘરે', 'ghare', 'home, at home']],
        drills: [
          { t: 'fill', gu: 'હું ___ જાઉં છું.', tr: 'huṁ ___ jāuṁ chhuṁ.', en: 'I’m going to the shop.', a: 'દુકાને', o: ['દુકાને', 'દુકાનમાં છે', 'દુકાન છે'], why: 'Going to a place: -એ.', tag: 'postposition' },
        ] },
      talk: { who: 'mummy', ctx: 'You’re putting on shoes.', gu: 'ક્યાં જાય છે?', tr: 'kyāṁ jāy chhe?', en: 'Where are you going?',
        o: [['દુકાને જાઉં છું. કંઈ લાવવું છે?', 'dukāne jāuṁ chhuṁ. kaṁī lāvvuṁ chhe?', 'To the shop. Need anything?', true, 'Thoughtful — Mummy will definitely give you a list.'],
            ['દુકાને જાય છે.', 'dukāne jāy chhe.', '(he/she goes)', false, 'About yourself: જાઉં છું.'],
            ['હું દુકાન છું.', 'huṁ dukān chhuṁ.', 'I am a shop.', false, 'Use the verb જવું.']] } },

    { id: 'L20', title: 'Directions', gu: 'રસ્તો', mins: 8,
      can: 'Ask for and give simple directions.',
      words: [
        w('ડાબી બાજુ', 'ḍābī bāju', 'left side', 'ḌAA-bee BAA-joo'),
        w('જમણી બાજુ', 'jamṇī bāju', 'right side', 'JUM-ṇee BAA-joo'),
        w('સીધા', 'sīdhā', 'straight', 'SEE-dhaa'),
        w('પાસે', 'pāse', 'near', 'PAA-say'),
        w('દૂર', 'dūr', 'far', 'door'),
      ],
      sents: [
        s('સીધા જાઓ.', 'sīdhā jāo.', 'Go straight.'),
        s('પછી ડાબી બાજુ વળો.', 'pachhī ḍābī bāju vaḷo.', 'Then turn left.'),
        s('મંદિર અહીંથી દૂર છે?', 'mandir ahīṁthī dūr chhe?', 'Is the mandir far from here?'),
        s('દુકાન પાસે જ છે.', 'dukān pāse ja chhe.', 'The shop is right nearby.'),
      ],
      grammar: { kind: 'grammar', title: 'જ adds emphasis',
        body: 'Put જ after a word to mean “right”, “just” or “only”. It’s tiny but everywhere in natural speech.',
        examples: [['પાસે જ', 'pāse ja', 'right nearby'], ['હમણાં જ', 'hamṇāṁ ja', 'just now'], ['એક જ', 'ek ja', 'only one']] },
      talk: { who: 'stranger', ctx: 'Someone stops you on the street.', gu: 'માફ કરજો, બજાર ક્યાં છે?', tr: 'māf karjo, bajār kyāṁ chhe?', en: 'Excuse me, where is the market?',
        o: [['સીધા જાઓ, પછી જમણી બાજુ.', 'sīdhā jāo, pachhī jamṇī bāju.', 'Go straight, then right.', true, 'Clear directions.'],
            ['બજાર દૂર જાઓ.', 'bajār dūr jāo.', 'Market far go.', false, 'Try: બજાર દૂર છે (the market is far).'],
            ['હું બજાર છું.', 'huṁ bajār chhuṁ.', 'I am the market.', false, 'Give directions instead.']] } },

    { id: 'L21', title: 'Shopping', gu: 'ખરીદી', mins: 9,
      can: 'Ask prices and bargain a little.',
      words: [
        w('કેટલા', 'keṭlā', 'how much / how many', 'KAYṬ-laa'),
        w('રૂપિયા', 'rūpiyā', 'rupees', 'ROO-pi-yaa'),
        w('મોંઘું', 'moṁghuṁ', 'expensive', 'MOṁ-ghuṁ'),
        w('સસ્તું', 'sastuṁ', 'cheap', 'SUS-tuṁ'),
        w('ઓછું', 'ochhuṁ', 'less', 'O-chhuṁ'),
      ],
      sents: [
        s('આ કેટલાનું છે?', 'ā keṭlānuṁ chhe?', 'How much is this?'),
        s('બહુ મોંઘું છે!', 'bahu moṁghuṁ chhe!', 'That’s very expensive!'),
        s('થોડું ઓછું કરો ને.', 'thoḍuṁ ochhuṁ karo ne.', 'Bring it down a little, please.'),
        s('કેટલા થયા?', 'keṭlā thayā?', 'How much does it come to?'),
      ],
      grammar: { kind: 'culture', title: 'Bargaining at the shaak market',
        body: 'At vegetable stalls and small shops, a little friendly bargaining is normal — at supermarkets and malls, it isn’t. The magic words are થોડું ઓછું કરો ને, said with a smile.',
        examples: [['ટામેટાં કેમ આપ્યાં?', 'ṭāmeṭāṁ kem āpyāṁ?', 'What’s the rate for tomatoes? (market idiom)'], ['છેલ્લું કેટલું?', 'chhelluṁ keṭluṁ?', 'What’s your final price?']] },
      talk: { who: 'shop', ctx: 'The shopkeeper names a price for a shawl.', gu: 'પાંચસો રૂપિયા.', tr: 'pāṁchso rūpiyā.', en: 'Five hundred rupees.',
        o: [['બહુ મોંઘું છે, થોડું ઓછું કરો ને.', 'bahu moṁghuṁ chhe, thoḍuṁ ochhuṁ karo ne.', 'Too expensive, bring it down a bit.', true, 'Classic.'],
            ['બહુ સસ્તું છે, ઓછું કરો.', 'bahu sastuṁ chhe, ochhuṁ karo.', 'It’s very cheap, reduce it.', false, 'If it’s cheap, why bargain? You mean મોંઘું.'],
            ['પાંચસો રૂપિયા છું.', 'pāṁchso rūpiyā chhuṁ.', 'I am 500 rupees.', false, 'Not quite!']] } },
  ]},
  { id: '2d', title: 'Feelings & needs', gu: 'મન', lessons: [
    { id: 'L22', title: 'Likes, wants, feelings', gu: 'ગમે છે', mins: 9,
      can: 'Say what you like, what you need and how you feel.',
      words: [
        w('ગમે છે', 'game chhe', 'likes (it pleases)', 'GUH-may chhay', 'મને ગમે છે = I like it.'),
        w('જોઈએ છે', 'joīe chhe', 'need / want', 'JO-ee-ay chhay', 'મને ચા જોઈએ છે = I want tea.'),
        w('ખુશ', 'khush', 'happy', 'khoosh'),
        w('થાકી ગયો', G('thākī gayo', 'thākī gaī'), 'tired (got tired)', 'THAA-kee guh-yo / guh-ee', 'Men say થાકી ગયો, women say થાકી ગઈ.', { guG: G('થાકી ગયો', 'થાકી ગઈ') }),
        w('બીમાર', 'bīmār', 'sick', 'bee-MAAR'),
      ],
      sents: [
        s('મને ઢોકળા ગમે છે.', 'mane ḍhoklā game chhe.', 'I like dhokla.'),
        s('મને ચા જોઈએ છે.', 'mane chā joīe chhe.', 'I want tea.'),
        s(G('હું બહુ થાકી ગયો છું.', 'હું બહુ થાકી ગઈ છું.'), G('huṁ bahu thākī gayo chhuṁ.', 'huṁ bahu thākī gaī chhuṁ.'), 'I’m really tired.'),
        s('આજે હું ખુશ છું.', 'āje huṁ khush chhuṁ.', 'I’m happy today.'),
      ],
      grammar: { kind: 'grammar', title: 'Liking and needing: “to me”',
        body: 'Like hunger, liking and needing happen to you: મને ગમે છે (it pleases me), મને જોઈએ છે (it is needed by me). The thing you like is the subject.',
        examples: [['મને ગુજરાતી ગમે છે.', 'mane gujarātī game chhe.', 'I like Gujarati.'], ['તમને શું જોઈએ છે?', 'tamne shuṁ joīe chhe?', 'What do you need?'], ['બાને ચા ગમે છે.', 'bāne chā game chhe.', 'Ba likes tea.']],
        drills: [
          { t: 'fill', gu: '___ ચા જોઈએ છે.', tr: '___ chā joīe chhe.', en: 'I want tea.', a: 'મને', o: ['મને', 'હું', 'મારી'], why: 'જોઈએ uses મને.', tag: 'dative' },
        ] },
      talk: { who: 'mummy', ctx: 'You flop onto the sofa.', gu: G('શું થયું? થાકી ગયો?', 'શું થયું? થાકી ગઈ?'), tr: G('shuṁ thayuṁ? thākī gayo?', 'shuṁ thayuṁ? thākī gaī?'), en: 'What happened? Tired?',
        o: [['હા, આજે બહુ કામ હતું.', 'hā, āje bahu kām hatuṁ.', 'Yes, lots of work today.', true, 'Natural.'],
            ['હા, મને થાક ગમે છે.', 'hā, mane thāk game chhe.', 'Yes, I like tiredness.', false, 'Probably not what you meant!'],
            ['ના, હું બીમાર છું.', 'nā, huṁ bīmār chhuṁ.', 'No, I’m sick.', true, 'Grammatical — expect Mummy to bring haldi-doodh.']] } },
  ]},
]},

/* ───────────────────────── LEVEL 3 ───────────────────────── */
{ n: 3, key: 'conversation', title: 'Conversation', gu: 'વાતચીત', tr: 'vātchīt',
  blurb: 'Answer naturally, describe things, and talk about past and future.',
  units: [
  { id: '3a', title: 'Asking & answering', gu: 'સવાલ-જવાબ', lessons: [
    { id: 'L23', title: 'About you', gu: 'તમારા વિશે', mins: 9,
      can: 'Say where you live and what you do.',
      words: [
        w('રહેવું', 'rahevuṁ', 'to live, stay', 'ruh-HAY-vuṁ'),
        w('કામ', 'kām', 'work', 'kaam'),
        w('ભણવું', 'bhaṇvuṁ', 'to study', 'BHUṆ-vuṁ'),
        w('શીખવું', 'shīkhvuṁ', 'to learn', 'SHEEKH-vuṁ'),
        w('નોકરી', 'nokrī', 'job', 'NOK-ree'),
      ],
      sents: [
        s('તમે ક્યાં રહો છો?', 'tame kyāṁ raho chho?', 'Where do you live?'),
        s('તમે શું કામ કરો છો?', 'tame shuṁ kām karo chho?', 'What work do you do?', 'Careful: શું કામ? on its own usually means “why?” — context tells you which.'),
        s('હું કૉલેજમાં ભણું છું.', 'huṁ kolejmāṁ bhaṇuṁ chhuṁ.', 'I study in college.'),
        s('હું નોકરી કરું છું.', 'huṁ nokrī karuṁ chhuṁ.', 'I work (have a job).'),
      ],
      talk: { who: 'uncle', ctx: 'An uncle at a wedding.', gu: 'શું કરે છે આજકાલ?', tr: 'shuṁ kare chhe ājkāl?', en: 'What are you up to these days?',
        o: [['હું કૉલેજમાં ભણું છું.', 'huṁ kolejmāṁ bhaṇuṁ chhuṁ.', 'I’m in college.', true, 'Good.'],
            ['હું નોકરી કરું છું.', 'huṁ nokrī karuṁ chhuṁ.', 'I’m working.', true, 'Good.'],
            ['હું કામ છું.', 'huṁ kām chhuṁ.', 'I am work.', false, 'Use a verb: કામ કરું છું.']] } },

    { id: 'L24', title: 'When you don’t understand', gu: 'સમજાયું નહીં', mins: 8,
      can: 'Keep a conversation going when you get lost.',
      words: [
        w('સમજાયું', 'samjāyuṁ', 'understood', 'sum-JAA-yuṁ'),
        w('ફરીથી', 'farīthī', 'again', 'fuh-REE-thee'),
        w('ધીમે', 'dhīme', 'slowly', 'DHEE-may'),
        w('ખબર', 'khabar', 'knowing, news', 'KHUB-ur', 'મને ખબર નથી = I don’t know.'),
        w('મતલબ', 'matlab', 'meaning', 'MUT-lub'),
      ],
      sents: [
        s('મને સમજાયું નહીં.', 'mane samjāyuṁ nahīṁ.', 'I didn’t understand.'),
        s('ફરીથી બોલો ને.', 'farīthī bolo ne.', 'Say it again, please.'),
        s('ધીમે ધીમે બોલો.', 'dhīme dhīme bolo.', 'Speak slowly, please.'),
        s('મને ખબર નથી.', 'mane khabar nathī.', 'I don’t know.'),
        s('આનો મતલબ શું?', 'āno matlab shuṁ?', 'What does this mean?'),
      ],
      grammar: { kind: 'culture', title: 'Your survival kit',
        body: 'Family members switch to English the moment you look lost. These five lines keep them in Gujarati. Use them without embarrassment — asking in Gujarati is itself practice.',
        examples: [['મને સમજાયું નહીં.', 'mane samjāyuṁ nahīṁ.', 'I didn’t understand.'], ['ધીમે ધીમે બોલો.', 'dhīme dhīme bolo.', 'Speak slowly.'], ['આનો મતલબ શું?', 'āno matlab shuṁ?', 'What does this mean?']] },
      talk: { who: 'ba', ctx: 'Ba says something very fast.', gu: 'તારા માટે મેં ખાસ ઢોકળા બનાવ્યા છે, ગરમ ગરમ ખાઈ લે.', tr: 'tārā māṭe meṁ khās ḍhoklā banāvyā chhe, garam garam khāī le.', en: 'I made dhokla specially for you, eat them while they’re hot.',
        o: [['બા, ધીમે ધીમે બોલો ને. મને સમજાયું નહીં.', 'bā, dhīme dhīme bolo ne. mane samjāyuṁ nahīṁ.', 'Ba, speak slowly please. I didn’t understand.', true, 'Perfect — and she’ll happily repeat it.'],
            ['મને ખબર છે.', 'mane khabar chhe.', 'I know.', false, 'Sounds dismissive.'],
            ['આવજો, બા.', 'āvjo, bā.', 'Bye, Ba.', false, 'You’d miss the dhokla!']] } },
  ]},
  { id: '3b', title: 'Describing', gu: 'વર્ણન', lessons: [
    { id: 'L25', title: 'Big, small, new, old', gu: 'મોટું, નાનું', mins: 8,
      can: 'Describe people and things.',
      words: [
        w('મોટું', 'moṭuṁ', 'big · older (person)', 'MO-ṭuṁ', 'મોટો ભાઈ = older brother.'),
        w('નાનું', 'nānuṁ', 'small · younger (person)', 'NAA-nuṁ', 'નાની બહેન = younger sister.'),
        w('સરસ', 'saras', 'nice, excellent', 'SUH-russ', 'Never changes. Everyone’s favourite compliment.'),
        w('નવું', 'navuṁ', 'new', 'NUH-vuṁ'),
        w('જૂનું', 'jūnuṁ', 'old (things)', 'JOO-nuṁ', 'For people’s age use મોટું.'),
      ],
      sents: [
        s('તમારું ઘર બહુ સરસ છે.', 'tamāruṁ ghar bahu saras chhe.', 'Your house is really nice.'),
        s('આ મારો નાનો ભાઈ છે.', 'ā māro nāno bhāī chhe.', 'This is my younger brother.'),
        s('મારી મોટી બહેન ડૉક્ટર છે.', 'mārī moṭī bahen ḍokṭar chhe.', 'My older sister is a doctor.'),
        s('આ ફોન નવો છે.', 'ā fon navo chhe.', 'This phone is new.'),
      ],
      grammar: { kind: 'grammar', title: 'Agreement, again',
        body: 'Same pattern as “my”: -ઓ for masculine, -ઈ for feminine, -ઉં for neuter. Now you’ll stack them: મારો નાનો ભાઈ — both words agree with ભાઈ.',
        examples: [['મારો નાનો ભાઈ', 'māro nāno bhāī', 'my younger brother'], ['મારી મોટી બહેન', 'mārī moṭī bahen', 'my older sister'], ['મારું નવું ઘર', 'māruṁ navuṁ ghar', 'my new house']],
        drills: [
          { t: 'fill', gu: 'મારી ___ બહેન', tr: 'mārī ___ bahen', en: 'my older sister', a: 'મોટી', o: ['મોટો', 'મોટી', 'મોટું'], why: 'બહેન is feminine.', tag: 'agreement' },
          { t: 'fill', gu: 'આ ફોન ___ છે.', tr: 'ā fon ___ chhe.', en: 'This phone is new.', a: 'નવો', o: ['નવો', 'નવી', 'નવું'], why: 'ફોન is masculine in Gujarati.', tag: 'agreement' },
        ] },
      talk: { who: 'masi', ctx: 'Masi asks about your new apartment.', gu: 'નવું ઘર કેવું છે?', tr: 'navuṁ ghar kevuṁ chhe?', en: 'How’s the new place?',
        o: [['બહુ સરસ છે, પણ થોડું નાનું છે.', 'bahu saras chhe, paṇ thoḍuṁ nānuṁ chhe.', 'Really nice, but a bit small.', true, 'Natural and specific.'],
            ['બહુ સરસ છો.', 'bahu saras chho.', 'You are very nice.', false, 'Sweet, but she asked about the house: છે.'],
            ['ઘર નાની છે.', 'ghar nānī chhe.', '(wrong ending)', false, 'ઘર is neuter → નાનું.']] } },

    { id: 'L26', title: 'Preferences', gu: 'પસંદ', mins: 8,
      can: 'Compare things and say what you prefer.',
      words: [
        w('વધારે', 'vadhāre', 'more', 'vuh-DHAA-ray'),
        w('કરતાં', 'kartāṁ', 'than', 'kur-TAAṁ'),
        w('કે', 'ke', 'or (in questions) · that', 'kay'),
        w('બંને', 'banne', 'both', 'BUN-nay'),
        w('સૌથી', 'sauthī', 'most (of all)', 'SOW-thee'),
      ],
      sents: [
        s('ચા કે કૉફી?', 'chā ke kofī?', 'Tea or coffee?'),
        s('મને ચા કરતાં કૉફી વધારે ગમે છે.', 'mane chā kartāṁ kofī vadhāre game chhe.', 'I like coffee more than tea.'),
        s('મને બંને ગમે છે.', 'mane banne game chhe.', 'I like both.'),
        s('મને ઢોકળા સૌથી વધારે ગમે છે.', 'mane ḍhoklā sauthī vadhāre game chhe.', 'I like dhokla the most.'),
      ],
      grammar: { kind: 'grammar', title: 'Comparing: A કરતાં B',
        body: '“More than A” is A કરતાં વધારે. “Most of all” is સૌથી વધારે. The adjective itself doesn’t change.',
        examples: [['ભાઈ મારા કરતાં મોટો છે.', 'bhāī mārā kartāṁ moṭo chhe.', 'Brother is older than me.'], ['આ સૌથી સરસ છે.', 'ā sauthī saras chhe.', 'This is the best.']] },
      talk: { who: 'mummy', ctx: 'Mummy has the kettle on.', gu: 'ચા કે કૉફી?', tr: 'chā ke kofī?', en: 'Tea or coffee?',
        o: [['ચા, મમ્મી. આભાર.', 'chā, mammī. ābhār.', 'Tea, Mummy. Thanks.', true, 'Simple and natural.'],
            ['મને બંને ગમે છે!', 'mane banne game chhe!', 'I like both!', true, 'Now she’ll decide for you.'],
            ['ચા કરતાં.', 'chā kartāṁ.', 'Than tea.', false, 'Unfinished comparison.']] } },
  ]},
  { id: '3c', title: 'Past & future', gu: 'ગઈ કાલ, આવતી કાલ', lessons: [
    { id: 'L27', title: 'Where I went', gu: 'હું ગયો / ગઈ', mins: 10,
      can: 'Say where you went and what happened.',
      words: [
        w('ગયો', G('gayo', 'gaī'), 'went', 'GUH-yo / GUH-ee', 'Men: ગયો. Women: ગઈ. Respect/plural: ગયા.', { guG: G('ગયો', 'ગઈ') }),
        w('આવ્યો', G('āvyo', 'āvī'), 'came', 'AAV-yo / AA-vee', 'Men: આવ્યો. Women: આવી. Respect/plural: આવ્યા.', { guG: G('આવ્યો', 'આવી') }),
        w('થયું', 'thayuṁ', 'happened', 'THUH-yuṁ', 'શું થયું? = What happened?'),
        w('હતો', G('hato', 'hatī'), 'was', 'HUH-to / HUH-tee', 'હતો / હતી / હતું — matches the subject.', { guG: G('હતો', 'હતી') }),
        w('પહોંચવું', 'pahoṁchvuṁ', 'to reach, arrive', 'puh-HOṁCH-vuṁ'),
      ],
      sents: [
        s(G('હું કાલે મંદિરે ગયો.', 'હું કાલે મંદિરે ગઈ.'), G('huṁ kāle mandire gayo.', 'huṁ kāle mandire gaī.'), 'I went to the mandir yesterday.'),
        s('શું થયું?', 'shuṁ thayuṁ?', 'What happened?'),
        s('પપ્પા ક્યારે આવ્યા?', 'pappā kyāre āvyā?', 'When did Dad come?'),
        s(G('હું સમયસર પહોંચી ગયો.', 'હું સમયસર પહોંચી ગઈ.'), G('huṁ samaysar pahoṁchī gayo.', 'huṁ samaysar pahoṁchī gaī.'), 'I got there on time.'),
      ],
      grammar: { kind: 'grammar', title: 'Past tense of “moving” verbs',
        body: 'For verbs with no object (go, come, sleep, arrive), the past form matches the subject’s gender. This is the one place your own gender shows up in Gujarati.',
        table: [['હું ગયો', 'huṁ gayo', 'I went (man)', '-યો'], ['હું ગઈ', 'huṁ gaī', 'I went (woman)', '-ઈ'], ['એ ગયા', 'e gayā', 'he/she went (respect) · they went', '-યા'], ['બાળક ગયું', 'bāḷak gayuṁ', 'the child went (neuter)', '-યું']],
        tip: 'Elders are always plural-respect: દાદા આવ્યા, બા આવ્યાં.',
        drills: [
          { t: 'pick', q: 'Priya says “I went home.”', o: ['હું ઘરે ગઈ.', 'હું ઘરે ગયો.'], a: 0, why: 'A woman says ગઈ.', tag: 'gender' },
          { t: 'fill', gu: 'પપ્પા ક્યારે ___?', tr: 'pappā kyāre ___?', en: 'When did Dad come?', a: 'આવ્યા', o: ['આવ્યો', 'આવ્યા', 'આવી'], why: 'Respect for Pappa → plural આવ્યા.', tag: 'respect' },
        ] },
      talk: { who: 'mummy', ctx: 'You came home late.', gu: G('કાલે ક્યાં ગયો હતો?', 'કાલે ક્યાં ગઈ હતી?'), tr: G('kāle kyāṁ gayo hato?', 'kāle kyāṁ gaī hatī?'), en: 'Where did you go yesterday?',
        o: [[G('મિત્રો સાથે ફરવા ગયો હતો.', 'મિત્રો સાથે ફરવા ગઈ હતી.'), G('mitro sāthe farvā gayo hato.', 'mitro sāthe farvā gaī hatī.'), 'I’d gone out with friends.', true, 'Natural past.'],
            ['હું મિત્રો સાથે જઈશ.', 'huṁ mitro sāthe jaīsh.', 'I will go with friends.', false, 'That’s future — she asked about yesterday.'],
            ['મિત્રો ક્યાં છે?', 'mitro kyāṁ chhe?', 'Where are the friends?', false, 'Answer her question.']] } },

    { id: 'L28', title: 'What I did', gu: 'મેં કર્યું', mins: 10,
      can: 'Say what you ate, saw and did.',
      words: [
        w('મેં', 'meṁ', 'I (did something)', 'meṁ — nasal e', 'The past-tense “I” for verbs with an object.'),
        w('ખાધું', 'khādhuṁ', 'ate', 'KHAA-dhuṁ'),
        w('કર્યું', 'karyuṁ', 'did', 'KUR-yuṁ'),
        w('જોયું', 'joyuṁ', 'saw, watched', 'JO-yuṁ'),
        w('લીધું', 'līdhuṁ', 'took', 'LEE-dhuṁ', 'Also finishes actions: જમી લીધું = finished eating.'),
      ],
      sents: [
        s('મેં જમી લીધું.', 'meṁ jamī līdhuṁ.', 'I’ve eaten.'),
        s('તેં શું કર્યું?', 'teṁ shuṁ karyuṁ?', 'What did you do?'),
        s('મેં ફિલ્મ જોઈ.', 'meṁ film joī.', 'I watched a film.'),
        s('મેં રોટલી ખાધી.', 'meṁ roṭlī khādhī.', 'I ate a rotli.'),
      ],
      grammar: { kind: 'grammar', title: 'The flip: મેં + object + verb',
        body: 'For past actions with an object (ate something, saw something), “I” becomes મેં and the verb matches the OBJECT — not you. Men and women say exactly the same thing.',
        table: [['મેં ભાત ખાધો', 'meṁ bhāt khādho', 'rice (masc.)', '-ઓ'], ['મેં રોટલી ખાધી', 'meṁ roṭlī khādhī', 'rotli (fem.)', '-ઈ'], ['મેં શાક ખાધું', 'meṁ shāk khādhuṁ', 'shaak (neut.)', '-ઉં']],
        tip: 'હું + past of an object verb is the #1 mistake heritage speakers make. મેં ખાધું, never હું ખાધું.',
        drills: [
          { t: 'fill', gu: 'મેં રોટલી ___.', tr: 'meṁ roṭlī ___.', en: 'I ate a rotli.', a: 'ખાધી', o: ['ખાધો', 'ખાધી', 'ખાધું'], why: 'The verb matches રોટલી (feminine).', tag: 'ergative' },
          { t: 'fill', gu: '___ જમી લીધું.', tr: '___ jamī līdhuṁ.', en: 'I’ve eaten.', a: 'મેં', o: ['હું', 'મેં', 'મને'], why: 'Past with લીધું → મેં.', tag: 'ergative' },
        ] },
      talk: { who: 'ba', ctx: 'Ba’s standard question.', gu: 'જમી લીધું?', tr: 'jamī līdhuṁ?', en: 'Have you eaten?',
        o: [['હા બા, મેં જમી લીધું.', 'hā bā, meṁ jamī līdhuṁ.', 'Yes Ba, I’ve eaten.', true, 'Perfect.'],
            ['હા, હું જમી લીધું.', 'hā, huṁ jamī līdhuṁ.', '(wrong “I”)', false, 'With લીધું, use મેં — or just drop it: હા, જમી લીધું.'],
            ['હા, જમી લીધું.', 'hā, jamī līdhuṁ.', 'Yes, done.', true, 'Dropping the subject is the most natural of all.']] } },

    { id: 'L29', title: 'Future plans', gu: 'હું આવીશ', mins: 10,
      can: 'Say what you and others will do.',
      words: [
        w('આવીશ', 'āvīsh', 'I will come', 'aa-VEESH'),
        w('જઈશ', 'jaīsh', 'I will go', 'juh-EESH'),
        w('કરીશ', 'karīsh', 'I will do', 'kuh-REESH'),
        w('આવશે', 'āvshe', 'he / she / they will come', 'AAV-shay'),
        w('કરશો', 'karsho', 'you (respect) will do', 'KUR-sho'),
      ],
      sents: [
        s('હું કાલે આવીશ.', 'huṁ kāle āvīsh.', 'I’ll come tomorrow.'),
        s('તમે ક્યારે આવશો?', 'tame kyāre āvsho?', 'When will you come?'),
        s('આપણે સાંજે જઈશું.', 'āpaṇe sāṁje jaīshuṁ.', 'We’ll go in the evening.'),
        s('એ પછી ફોન કરશે.', 'e pachhī fon karshe.', 'He’ll call later.'),
      ],
      grammar: { kind: 'grammar', title: 'Future endings',
        body: 'Add the future ending to the stem. No gender to worry about!',
        tip: 'In fast speech you’ll also hear તું આવશે? instead of તું આવીશ? — both are understood, but -ઈશ is the standard form.',
        table: [['હું / તું', '-ઈશ', 'karīsh', 'હું કરીશ'], ['એ / તેઓ', '-શે', 'karshe', 'એ કરશે'], ['અમે / આપણે', '-ઈશું', 'karīshuṁ', 'આપણે કરીશું'], ['તમે', '-શો', 'karsho', 'તમે કરશો']],
        drills: [
          { t: 'fill', gu: 'હું કાલે ___.', tr: 'huṁ kāle ___.', en: 'I’ll come tomorrow.', a: 'આવીશ', o: ['આવીશ', 'આવશે', 'આવશો'], why: 'હું → -ઈશ.', tag: 'verb-ending' },
          { t: 'fill', gu: 'તમે ક્યારે ___?', tr: 'tame kyāre ___?', en: 'When will you come?', a: 'આવશો', o: ['આવીશ', 'આવશે', 'આવશો'], why: 'તમે → -શો.', tag: 'verb-ending' },
        ] },
      talk: { who: 'nani', ctx: 'Nani on a video call from India.', gu: 'તું ક્યારે આવીશ?', tr: 'tuṁ kyāre āvīsh?', en: 'When will you come?',
        o: [['હું આવતા મહિને આવીશ, નાની.', 'huṁ āvtā mahine āvīsh, nānī.', 'I’ll come next month, Nani.', true, 'She’s already planning the menu.'],
            ['હું આવતા મહિને આવશે.', 'huṁ āvtā mahine āvshe.', '(wrong ending)', false, 'હું → આવીશ.'],
            ['હું ગઈ કાલે આવ્યો.', 'huṁ gaī kāle āvyo.', 'I came yesterday.', false, 'Past tense — she asked about the future.']] } },

    { id: 'L30', title: 'Making plans', gu: 'ચાલો, મળીએ', mins: 9,
      can: 'Suggest plans and agree on a time.',
      words: [
        w('આપણે', 'āpaṇe', 'we (including you)', 'AA-puh-ṇay'),
        w('અમે', 'ame', 'we (not including you)', 'UH-may'),
        w('ચાલો', 'chālo', 'let’s go / come on', 'CHAA-lo'),
        w('ફાવશે', 'fāvshe', 'will suit (you)', 'FAAV-shay', 'કાલે ફાવશે? = Does tomorrow work?'),
        w('ફરવા', 'farvā', 'out (for fun)', 'FUR-vaa', 'ફરવા જઈએ? = Shall we go out?'),
      ],
      sents: [
        s('ચાલો, શનિવારે મળીએ.', 'chālo, shanivāre maḷīe.', 'Let’s meet on Saturday.'),
        s('આપણે ફરવા જઈએ?', 'āpaṇe farvā jaīe?', 'Shall we go out?'),
        s('કાલે ફાવશે?', 'kāle fāvshe?', 'Does tomorrow work?'),
        s('અમે મંદિરે જઈએ છીએ.', 'ame mandire jaīe chhīe.', 'We’re going to the mandir (not you).'),
      ],
      grammar: { kind: 'grammar', title: 'Two kinds of “we”',
        body: 'Gujarati has an inclusive “we” (આપણે — you and me) and an exclusive “we” (અમે — us, not you). Mixing them up changes who’s invited!',
        examples: [['આપણે જઈએ?', 'āpaṇe jaīe?', 'Shall we (you and I) go?'], ['અમે જઈએ છીએ.', 'ame jaīe chhīe.', 'We’re going (without you).']],
        drills: [
          { t: 'pick', q: 'Tell Mummy (who is coming along): “We’re going to the mandir.”', o: ['આપણે મંદિરે જઈએ છીએ.', 'અમે મંદિરે જઈએ છીએ.'], a: 0, why: 'She’s included → આપણે.', tag: 'pronoun' },
        ] },
      talk: { who: 'cousin', ctx: 'Your cousin texts.', gu: 'શનિવારે ફરવા જઈએ?', tr: 'shanivāre farvā jaīe?', en: 'Go out on Saturday?',
        o: [['હા, ચાલો! ક્યારે મળીએ?', 'hā, chālo! kyāre maḷīe?', 'Yes, let’s! When shall we meet?', true, 'Enthusiastic and natural.'],
            ['હા, અમે જઈશું.', 'hā, ame jaīshuṁ.', 'Yes, we (not you) will go.', false, 'અમે leaves your cousin out!'],
            ['શનિવારે ગયા.', 'shanivāre gayā.', 'Went on Saturday.', false, 'That’s past tense.']] } },
  ]},
]},

/* ───────────────────────── LEVEL 4 ───────────────────────── */
{ n: 4, key: 'grammar', title: 'Grammar in use', gu: 'વ્યાકરણ', tr: 'vyākaraṇ',
  blurb: 'Word order, negation, postpositions, verb pairs and agreement — through real sentences.',
  units: [
  { id: '4a', title: 'Sentence engine', gu: 'વાક્ય', lessons: [
    { id: 'L31', title: 'Word order & pronouns', gu: 'કર્તા-કર્મ-ક્રિયાપદ', mins: 10,
      can: 'Build longer sentences in natural order.',
      words: [
        w('એ', 'e', 'he / she / that', 'ay', 'Everyday “he/she”. More formal: તે.'),
        w('તેઓ', 'teo', 'they (formal)', 'TAY-o', 'Casual: એ લોકો.'),
        w('લોકો', 'loko', 'people', 'LO-ko'),
        w('રોજ', 'roj', 'every day', 'roj'),
        w('દર', 'dar', 'every (+ day/week)', 'dur', 'દર રવિવારે = every Sunday.'),
      ],
      sents: [
        s('હું રોજ સવારે ચા પીઉં છું.', 'huṁ roj savāre chā pīuṁ chhuṁ.', 'I drink tea every morning.'),
        s('અમે દર રવિવારે મંદિરે જઈએ છીએ.', 'ame dar ravivāre mandire jaīe chhīe.', 'We go to the mandir every Sunday.'),
        s('એ લોકો કાલે આવશે.', 'e loko kāle āvshe.', 'They’ll come tomorrow.'),
        s('તેઓ ડૉક્ટર છે.', 'teo ḍokṭar chhe.', 'They are doctors.'),
      ],
      grammar: { kind: 'grammar', title: 'Subject → time → place → object → verb',
        body: 'The verb goes last. Everything else lines up before it, usually in this order. Once this feels normal, long sentences become easy.',
        examples: [['હું | કાલે | ઘરે | જઈશ.', 'huṁ | kāle | ghare | jaīsh.', 'I | tomorrow | home | will go.'], ['અમે | દર રવિવારે | મંદિરે | જઈએ છીએ.', 'ame | dar ravivāre | mandire | jaīe chhīe.', 'We | every Sunday | to the mandir | go.']],
        tip: 'Spoken Gujarati is flexible — you’ll hear “શું કરે છે આજકાલ?” with the verb early. But the default is verb-last.' } },

    { id: 'L32', title: 'Saying no', gu: 'નથી, નહીં, ન', mins: 10,
      can: 'Make any sentence negative, including commands.',
      words: [
        w('નહીં', 'nahīṁ', 'not (past / emphatic)', 'nuh-HEEṁ', 'મને સમજાયું નહીં. · હું નહીં આવું.'),
        w('ન', 'na', 'don’t (with commands)', 'nuh', 'ચિંતા ન કરો = don’t worry.'),
        w('કંઈ નહીં', 'kaṁī nahīṁ', 'nothing / never mind', 'KUṁ-ee nuh-HEEṁ'),
        w('ચિંતા', 'chintā', 'worry', 'CHIN-taa'),
        w('ક્યારેય', 'kyāreya', 'ever', 'KYAA-ray-yuh', 'ક્યારેય નહીં = never.'),
      ],
      sents: [
        s(G('હું આજે ઑફિસ નથી જતો.', 'હું આજે ઑફિસ નથી જતી.'), G('huṁ āje ofis nathī jato.', 'huṁ āje ofis nathī jatī.'), 'I’m not going to the office today.'),
        s('ચિંતા ન કરો.', 'chintā na karo.', 'Don’t worry.'),
        s('મને ખબર નથી.', 'mane khabar nathī.', 'I don’t know.'),
        s('કંઈ નહીં, ચાલશે.', 'kaṁī nahīṁ, chālshe.', 'Never mind, it’s fine.'),
      ],
      grammar: { kind: 'grammar', title: 'Three ways to say no',
        body: 'નથી for “is not” and the present. નહીં for past and “won’t”. ન (or ના) for “don’t” commands. Present negatives use the -તો/-તી form: હું નથી જતો (m) / જતી (f).',
        table: [['નથી', 'nathī', 'present / is not', 'હું ઘરે નથી.'], ['નહીં', 'nahīṁ', 'past / won’t', 'મને સમજાયું નહીં.'], ['ન', 'na', 'don’t (command)', 'ચિંતા ન કરો.']],
        drills: [
          { t: 'pick', q: 'Tell Dada “Don’t worry.”', o: ['ચિંતા ન કરો.', 'ચિંતા નથી કરો.'], a: 0, why: 'Commands use ન.', tag: 'negation' },
          { t: 'fill', gu: 'મને સમજાયું ___.', tr: 'mane samjāyuṁ ___.', en: 'I didn’t understand.', a: 'નહીં', o: ['નહીં', 'ન', 'નથી'], why: 'After a past form, use નહીં.', tag: 'negation' },
        ] } },

    { id: 'L33', title: 'Of, to, with, for', gu: 'નો, ને, સાથે', mins: 10,
      can: 'Say whose something is, who it’s for, and who you’re with.',
      words: [
        w('નો / ની / નું', 'no / nī / nuṁ', 'of, ’s', 'no / nee / nuṁ', 'Matches the thing owned: રામનો ભાઈ, રામની બહેન.'),
        w('ને', 'ne', 'to (a person)', 'nay', 'દાદાને ફોન કરો = call Dada.'),
        w('સાથે', 'sāthe', 'with', 'SAA-thay'),
        w('માટે', 'māṭe', 'for', 'MAA-ṭay'),
        w('થી', 'thī', 'from, by', 'thee', 'ઘરેથી = from home.'),
      ],
      sents: [
        s('આ મમ્મીની ચા છે.', 'ā mammīnī chā chhe.', 'This is Mummy’s tea.'),
        s('હું ભાઈ સાથે જાઉં છું.', 'huṁ bhāī sāthe jāuṁ chhuṁ.', 'I’m going with my brother.'),
        s('આ તમારા માટે છે.', 'ā tamārā māṭe chhe.', 'This is for you.'),
        s('દાદાને ફોન કરો.', 'dādāne fon karo.', 'Call Dada.'),
      ],
      grammar: { kind: 'grammar', title: '’s that agrees',
        body: 'Gujarati “’s” (-નો/-ની/-નું) sticks to the owner but agrees with the thing owned — exactly like મારો/મારી/મારું.',
        table: [['પપ્પાનો ફોન', 'pappāno fon', 'Dad’s phone (masc.)', '-નો'], ['પપ્પાની ચા', 'pappānī chā', 'Dad’s tea (fem.)', '-ની'], ['પપ્પાનું ઘર', 'pappānuṁ ghar', 'Dad’s house (neut.)', '-નું']],
        drills: [
          { t: 'fill', gu: 'આ પપ્પા___ ફોન છે.', tr: 'ā pappā___ fon chhe.', en: 'This is Dad’s phone.', a: 'નો', o: ['નો', 'ની', 'નું'], why: 'ફોન is masculine → -નો.', tag: 'postposition' },
          { t: 'fill', gu: 'આ મમ્મી___ ચોપડી છે.', tr: 'ā mammī___ chopḍī chhe.', en: 'This is Mummy’s book.', a: 'ની', o: ['નો', 'ની', 'નું'], why: 'ચોપડી is feminine → -ની.', tag: 'postposition' },
        ] } },
  ]},
  { id: '4b', title: 'Verbs that change', gu: 'ક્રિયાપદ', lessons: [
    { id: 'L34', title: 'Verb pairs', gu: 'જમી લે, સૂઈ જા', mins: 10,
      can: 'Use the verb pairs that make Gujarati sound natural.',
      words: [
        w('જમી લે', 'jamī le', 'go ahead and eat', 'JUH-mee lay'),
        w('સૂઈ જા', 'sūī jā', 'go to sleep', 'SOO-ee jaa'),
        w('આપી દે', 'āpī de', 'give it (over)', 'AA-pee day'),
        w('ભૂલી ગયો', G('bhūlī gayo', 'bhūlī gaī'), 'forgot', 'BHOO-lee guh-yo', 'Women: ભૂલી ગઈ.', { guG: G('ભૂલી ગયો', 'ભૂલી ગઈ') }),
        w('થઈ જશે', 'thaī jashe', 'it will get done / become', 'TUH-ee juh-shay'),
      ],
      sents: [
        s('જમી લે, ઠંડું થઈ જશે.', 'jamī le, ṭhaṇḍuṁ thaī jashe.', 'Eat — it’ll get cold.'),
        s(G('સોરી, હું ભૂલી ગયો.', 'સોરી, હું ભૂલી ગઈ.'), G('sorī, huṁ bhūlī gayo.', 'sorī, huṁ bhūlī gaī.'), 'Sorry, I forgot.'),
        s('ચાવી આપી દે.', 'chāvī āpī de.', 'Hand over the key.'),
        s('હવે સૂઈ જા.', 'have sūī jā.', 'Go to sleep now.'),
      ],
      grammar: { kind: 'grammar', title: 'Main verb + helper',
        body: 'Gujarati loves pairing a verb (in -ઈ) with a helper. લેવું = do it (for yourself / finish it). જવું = change of state. દેવું = do it (for someone / get it over with). Without the helper, sentences sound bookish.',
        examples: [['જમી લે', 'jamī le', 'eat (go on, finish up)'], ['થાકી ગયો', 'thākī gayo', 'got tired'], ['આપી દે', 'āpī de', 'give it away / hand it over']],
        tip: 'The helper takes all the endings: જમી લીધું, જમી લઈશ, જમી લે.' } },

    { id: 'L35', title: 'Asking nicely', gu: 'આવો, બેસો', mins: 9,
      can: 'Give polite commands and soften requests.',
      words: [
        w('આવો', 'āvo', 'come (in) — respectful', 'AA-vo', 'Also the welcome word at the door.'),
        w('બેસો', 'beso', 'sit — respectful', 'BAY-so'),
        w('જરા', 'jarā', 'a bit (softener)', 'juh-RAA', 'જરા પાણી આપ ને = could you give me some water.'),
        w('ધ્યાન રાખજો', 'dhyān rākhjo', 'take care', 'DHYAAN RAAKH-jo'),
        w('તો', 'to', 'just (softener) · then', 'toe', 'આ જો તો = just look at this.'),
      ],
      sents: [
        s('આવો, બેસો.', 'āvo, beso.', 'Come in, have a seat.'),
        s('જરા પાણી આપ ને.', 'jarā pāṇī āp ne.', 'Could you give me some water?'),
        s('ધ્યાન રાખજો.', 'dhyān rākhjo.', 'Take care.'),
        s('આ જો તો.', 'ā jo to.', 'Just look at this.'),
      ],
      grammar: { kind: 'grammar', title: 'Three levels of command',
        body: 'Close: બેસ. Respectful: બેસો. Extra-polite or “later”: બેસજો. Then soften anything with જરા, ને or તો.',
        table: [['બેસ', 'bes', 'to a sibling / friend', 'close'], ['બેસો', 'beso', 'to an elder / guest', 'respect'], ['બેસજો', 'besjo', 'please do (sit)', 'polite / later']],
        drills: [
          { t: 'pick', q: 'An elder guest arrives. You say:', o: ['આવો, બેસો.', 'આવ, બેસ.'], a: 0, why: 'Guests and elders get the respectful form.', tag: 'respect' },
        ] } },

    { id: 'L36', title: 'He, she, it', gu: 'લિંગ', mins: 10,
      can: 'Guess and use noun gender confidently.',
      words: [
        w('છોકરો', 'chhokro', 'boy', 'CHHOK-ro'),
        w('છોકરી', 'chhokrī', 'girl', 'CHHOK-ree'),
        w('છોકરું', 'chhokruṁ', 'kid, child', 'CHHOK-ruṁ'),
        w('તોફાની', 'tofānī', 'naughty', 'toe-FAA-nee'),
        w('સારો', 'sāro', 'good (masc.)', 'SAA-ro', 'સારો / સારી / સારું.'),
      ],
      sents: [
        s('એ સારો છોકરો છે.', 'e sāro chhokro chhe.', 'He’s a good boy.'),
        s('મારી દીકરી નાની છે.', 'mārī dīkrī nānī chhe.', 'My daughter is little.'),
        s('આ છોકરું બહુ તોફાની છે.', 'ā chhokruṁ bahu tofānī chhe.', 'This kid is very naughty.'),
        s('ઘર મોટું છે.', 'ghar moṭuṁ chhe.', 'The house is big.'),
      ],
      grammar: { kind: 'grammar', title: 'Three genders',
        body: 'Words ending in -ઓ are usually masculine, -ઈ feminine, -ઉં neuter. Other words you just learn — but anything that agrees with them will tell you.',
        table: [['સારો છોકરો', 'sāro chhokro', 'masculine', '-ઓ'], ['સારી છોકરી', 'sārī chhokrī', 'feminine', '-ઈ'], ['સારું છોકરું', 'sāruṁ chhokruṁ', 'neuter', '-ઉં']],
        drills: [
          { t: 'fill', gu: 'ઘર ___ છે.', tr: 'ghar ___ chhe.', en: 'The house is big.', a: 'મોટું', o: ['મોટો', 'મોટી', 'મોટું'], why: 'ઘર is neuter.', tag: 'agreement' },
          { t: 'fill', gu: 'એ ___ છોકરી છે.', tr: 'e ___ chhokrī chhe.', en: 'She’s a good girl.', a: 'સારી', o: ['સારો', 'સારી', 'સારું'], why: 'છોકરી is feminine.', tag: 'agreement' },
        ] } },
  ]},
]},

/* ───────────────────────── LEVEL 5 ───────────────────────── */
{ n: 5, key: 'natural', title: 'Natural speech', gu: 'સહજ ગુજરાતી', tr: 'sahaj gujarātī',
  blurb: 'How family actually talks: short forms, particles, reactions and speed.',
  units: [
  { id: '5a', title: 'Home talk', gu: 'ઘરની ભાષા', lessons: [
    { id: 'L37', title: 'Home Gujarati', gu: 'ઘરનું ગુજરાતી', mins: 9,
      can: 'Understand and use the short forms you hear at home.',
      words: [
        w('શું ચાલે છે?', 'shuṁ chāle chhe?', 'what’s going on?', 'shuṁ CHAA-lay chhay'),
        w('ક્યાં ચાલ્યો?', G('kyāṁ chālyo?', 'kyāṁ chālī?'), 'where are you off to?', 'kyaaṁ CHAAL-yo', 'To a woman: ક્યાં ચાલી?', { guG: G('ક્યાં ચાલ્યો?', 'ક્યાં ચાલી?') }),
        w('આ આવ્યો!', G('ā āvyo!', 'ā āvī!'), 'coming! (right away)', 'aa AAV-yo', 'Literally “here, I came!” Women: આ આવી!', { guG: G('આ આવ્યો!', 'આ આવી!') }),
        w('પત્યું?', 'patyuṁ?', 'done? finished?', 'PUT-yuṁ'),
        w('જમવા ચાલો', 'jamvā chālo', 'come and eat', 'JUM-vaa CHAA-lo'),
      ],
      sents: [
        s('શું ચાલે છે?', 'shuṁ chāle chhe?', 'What’s up?'),
        s(G('આ આવ્યો, એક મિનિટ!', 'આ આવી, એક મિનિટ!'), G('ā āvyo, ek miniṭ!', 'ā āvī, ek miniṭ!'), 'Coming, one minute!'),
        s('હોમવર્ક પત્યું?', 'homvark patyuṁ?', 'Homework done?'),
        s('ચાલો, જમવા ચાલો!', 'chālo, jamvā chālo!', 'Come on, come and eat!'),
      ],
      grammar: { kind: 'register', title: 'Textbook, natural, very casual',
        body: 'The same question comes in three registers. Textbooks teach the first. Families use the second and third. Use casual forms only with people you’d use તું with.',
        table: [['Textbook', 'tame kyāṁ jāo chho?', 'તમે ક્યાં જાઓ છો?', 'formal, correct, a bit stiff'], ['Natural', 'kyāṁ jāy chhe?', 'ક્યાં જાય છે?', 'everyday, to a sibling'], ['Very casual', 'kyāṁ chālyo?', 'ક્યાં ચાલ્યો?', 'teasing, warm, at home']] },
      talk: { who: 'mummy', ctx: 'Mummy shouts from downstairs.', gu: 'જમવા ચાલો!', tr: 'jamvā chālo!', en: 'Come eat!',
        o: [[G('આ આવ્યો!', 'આ આવી!'), G('ā āvyo!', 'ā āvī!'), 'Coming!', true, 'Exactly what a Gujarati kid shouts back.'],
            ['હું આવીશ.', 'huṁ āvīsh.', 'I will come.', false, 'Sounds like “I’ll come… eventually”. Expect a second, louder call.'],
            ['જમવાનું ક્યાં છે?', 'jamvānuṁ kyāṁ chhe?', 'Where’s the food?', false, 'She just told you!']] } },

    { id: 'L38', title: 'Little words', gu: 'તો, ને, જ, પણ', mins: 9,
      can: 'Use the particles that make speech sound native.',
      words: [
        w('પણ', 'paṇ', 'also, too · but', 'puṇ', 'હું પણ = me too.'),
        w('ખરું ને?', 'kharuṁ ne?', 'right? isn’t it?', 'KHUH-ruṁ nay'),
        w('યાર', 'yār', 'buddy, man (casual)', 'yaar', 'Only with friends and siblings.'),
        w('હવે', 'have', 'now (from now on)', 'huh-VAY'),
        w('પાછું', 'pāchhuṁ', 'back · again', 'PAA-chhuṁ'),
      ],
      sents: [
        s('તું પણ આવ ને!', 'tuṁ paṇ āv ne!', 'You come too!'),
        s('હું જ કરીશ.', 'huṁ ja karīsh.', 'I’ll do it myself.'),
        s('સરસ છે, ખરું ને?', 'saras chhe, kharuṁ ne?', 'It’s nice, isn’t it?'),
        s('આ લાવ તો.', 'ā lāv to.', 'Bring that here, would you.'),
      ],
      grammar: { kind: 'grammar', title: 'Particles carry the tone',
        body: 'These tiny words don’t change the meaning — they change the feeling. Learners who skip them sound like a textbook.',
        table: [['ને', 'ne', 'friendly push', 'ચાલ ને!'], ['તો', 'to', '“just”, softener', 'આ જો તો.'], ['જ', 'ja', 'only / exactly', 'હું જ આવીશ.'], ['પણ', 'paṇ', 'too / also', 'હું પણ આવીશ.']] } },
  ]},
  { id: '5b', title: 'Expressions', gu: 'રૂઢિપ્રયોગ', lessons: [
    { id: 'L39', title: 'Everyday expressions', gu: 'ચાલશે, વાંધો નહીં', mins: 9,
      can: 'Use the phrases that smooth everyday life.',
      words: [
        w('ચાલશે', 'chālshe', 'that’ll do, it’s fine', 'CHAAL-shay', 'Literally “it will walk”. The most Gujarati word there is.'),
        w('વાંધો નહીં', 'vāṁdho nahīṁ', 'no problem', 'VAAṁ-dho nuh-HEEṁ'),
        w('મજા આવી', 'majā āvī', 'it was fun', 'muh-JAA AA-vee'),
        w('ધ્યાન રાખજે', 'dhyān rākhje', 'take care (close)', 'DHYAAN RAAKH-jay', 'To elders: ધ્યાન રાખજો.'),
        w('શાંતિ રાખ', 'shānti rākh', 'calm down, relax', 'SHAAN-ti RAAKH'),
      ],
      sents: [
        s('ચા નથી? ચાલશે, પાણી આપો.', 'chā nathī? chālshe, pāṇī āpo.', 'No tea? That’s fine, water please.'),
        s('વાંધો નહીં, કાલે કરજો.', 'vāṁdho nahīṁ, kāle karjo.', 'No problem, do it tomorrow.'),
        s('બહુ મજા આવી!', 'bahu majā āvī!', 'That was so much fun!'),
        s('શાંતિ રાખ, બધું થઈ જશે.', 'shānti rākh, badhuṁ thaī jashe.', 'Relax, everything will get done.'),
      ],
      talk: { who: 'friend', ctx: 'Your friend arrives late.', gu: G('સોરી યાર, હું મોડો પડ્યો.', 'સોરી યાર, હું મોડી પડી.'), tr: G('sorī yār, huṁ moḍo paḍyo.', 'sorī yār, huṁ moḍī paḍī.'), en: 'Sorry, I’m late.',
        o: [['વાંધો નહીં!', 'vāṁdho nahīṁ!', 'No problem!', true, 'Easy-going and natural.'],
            ['ચાલશે, ચાલશે.', 'chālshe, chālshe.', 'It’s fine, it’s fine.', true, 'Very Gujarati.'],
            ['મજા આવી!', 'majā āvī!', 'That was fun!', false, 'Nothing fun has happened yet.']] } },

    { id: 'L40', title: 'Reactions', gu: 'અરે વાહ!', mins: 8,
      can: 'React naturally when people tell you things.',
      words: [
        w('અરે વાહ!', 'are vāh!', 'oh wow! (nice)', 'uh-RAY VAAH'),
        w('સાચે?', 'sāche?', 'really?', 'SAA-chay'),
        w('હાસ્તો', 'hāsto', 'of course (casual)', 'HAAS-to'),
        w('બસ', 'bas', 'enough · that’s all', 'bus'),
        w('અભિનંદન', 'abhinandan', 'congratulations', 'uh-bhi-NUN-dun'),
      ],
      sents: [
        s('અરે વાહ, સરસ!', 'are vāh, saras!', 'Oh wow, great!'),
        s('સાચે? મને ખબર જ નહોતી.', 'sāche? mane khabar ja nahotī.', 'Really? I had no idea.'),
        s('બસ, બહુ થયું.', 'bas, bahu thayuṁ.', 'Enough, that’s plenty.'),
        s('હાસ્તો, ચાલો!', 'hāsto, chālo!', 'Of course, let’s go!'),
      ],
      talk: { who: 'cousin', ctx: 'Your cousin has big news.', gu: 'મને નોકરી મળી ગઈ!', tr: 'mane nokrī maḷī gaī!', en: 'I got the job!',
        o: [['અરે વાહ! અભિનંદન!', 'are vāh! abhinandan!', 'Wow! Congratulations!', true, 'Perfect reaction.'],
            ['બસ, બહુ થયું.', 'bas, bahu thayuṁ.', 'Enough already.', false, 'That sounds annoyed!'],
            ['સાચે? મને ખબર નથી.', 'sāche? mane khabar nathī.', 'Really? I don’t know.', false, '“I don’t know” doesn’t fit here.']] } },

    { id: 'L41', title: 'Listening at family speed', gu: 'ઝડપથી', mins: 10,
      can: 'Follow fast, everyday family sentences.',
      words: [
        w('એટલે', 'eṭle', 'so · that means', 'AYṬ-lay'),
        w('પછી', 'pachhī', 'then, later', 'PUH-chhee'),
        w('બધું', 'badhuṁ', 'everything', 'BUH-dhuṁ'),
        w('કંઈક', 'kaṁīk', 'something', 'KUṁ-eek'),
        w('મોડું', 'moḍuṁ', 'late', 'MO-ḍuṁ', 'મોડું થાય છે = it’s getting late.'),
      ],
      sents: [
        s('હવે શું કરીએ?', 'have shuṁ karīe?', 'What shall we do now?'),
        s('બધું બરાબર છે?', 'badhuṁ barābar chhe?', 'Is everything okay?'),
        s('કંઈક ખાઈ લે, પછી જા.', 'kaṁīk khāī le, pachhī jā.', 'Eat something, then go.'),
        s('જલદી કર, મોડું થાય છે.', 'jaldī kar, moḍuṁ thāy chhe.', 'Hurry up, it’s getting late.'),
      ],
      focus: ['listening'],
      read: { title: 'Morning rush',
        lines: [['મમ્મી: ઊઠ, મોડું થાય છે!', 'mammī: ūṭh, moḍuṁ thāy chhe!', 'Mummy: Get up, it’s getting late!'],
                ['ભાઈ: હા, ઊઠું છું, ઊઠું છું.', 'bhāī: hā, ūṭhuṁ chhuṁ, ūṭhuṁ chhuṁ.', 'Brother: Yes, I’m getting up, I’m getting up.'],
                ['મમ્મી: કંઈક ખાઈ લે, પછી જા.', 'mammī: kaṁīk khāī le, pachhī jā.', 'Mummy: Eat something, then go.'],
                ['ભાઈ: ટાઇમ નથી, મમ્મી! આવજો!', 'bhāī: ṭāim nathī, mammī! āvjo!', 'Brother: No time, Mummy! Bye!']],
        qs: [{ q: 'Why is Mummy calling?', o: ['It’s getting late', 'Food is ready', 'Guests arrived'], a: 0 },
             { q: 'Does the brother eat?', o: ['No — he has no time', 'Yes, a full meal', 'He eats at school'], a: 0 }] } },
  ]},
]},

/* ───────────────────────── LEVEL 6 ───────────────────────── */
{ n: 6, key: 'fluency', title: 'Fluency', gu: 'પ્રવાહિતા', tr: 'pravāhitā',
  blurb: 'Tell stories, give opinions, and talk about festivals and faith.',
  units: [
  { id: '6a', title: 'Stories & opinions', gu: 'વાર્તા અને વિચાર', lessons: [
    { id: 'L42', title: 'Telling a story', gu: 'વાર્તા', mins: 12,
      can: 'Tell what happened, in order.',
      words: [
        w('પહેલાં', 'pahelāṁ', 'first · before', 'puh-HAY-laaṁ'),
        w('અચાનક', 'achānak', 'suddenly', 'uh-CHAA-nuk'),
        w('છેવટે', 'chhevaṭe', 'finally, in the end', 'CHHAY-vuh-ṭay'),
        w('ત્યારે', 'tyāre', 'then, at that time', 'TYAA-ray'),
        w('ગયા', 'gayā', 'last (week/Sunday)', 'GUH-yaa', 'ગયા રવિવારે = last Sunday.'),
      ],
      sents: [
        s('પહેલાં અમે આરતી જોઈ.', 'pahelāṁ ame ārtī joī.', 'First we watched the aarti.'),
        s('પછી અમે પ્રસાદ લીધો.', 'pachhī ame prasād līdho.', 'Then we took prasad.'),
        s('અચાનક વરસાદ પડવા લાગ્યો.', 'achānak varsād paḍvā lāgyo.', 'Suddenly it started to rain.'),
        s('છેવટે અમે ઘરે પહોંચ્યા.', 'chhevaṭe ame ghare pahoṁchyā.', 'Finally we reached home.'),
      ],
      read: { title: 'A rainy Sunday',
        lines: [['ગયા રવિવારે અમે બધા મંદિરે ગયા.', 'gayā ravivāre ame badhā mandire gayā.', 'Last Sunday we all went to the mandir.'],
                ['પહેલાં અમે આરતી જોઈ, પછી પ્રસાદ લીધો.', 'pahelāṁ ame ārtī joī, pachhī prasād līdho.', 'First we watched the aarti, then took prasad.'],
                ['અચાનક વરસાદ પડવા લાગ્યો!', 'achānak varsād paḍvā lāgyo!', 'Suddenly it started to rain!'],
                ['છેવટે અમે ભીંજાઈને ઘરે પહોંચ્યા, પણ બહુ મજા આવી.', 'chhevaṭe ame bhīṁjāīne ghare pahoṁchyā, paṇ bahu majā āvī.', 'We finally got home soaked, but it was great fun.']],
        qs: [{ q: 'What did they do first?', o: ['Watched the aarti', 'Took prasad', 'Went home'], a: 0 },
             { q: 'What happened suddenly?', o: ['It started raining', 'The mandir closed', 'Ba arrived'], a: 0 },
             { q: 'How was the day?', o: ['Fun, despite the rain', 'Boring', 'Stressful'], a: 0 }] } },

    { id: 'L43', title: 'Giving opinions', gu: 'મારા મતે', mins: 12,
      can: 'Say what you think and why.',
      words: [
        w('મને લાગે છે કે', 'mane lāge chhe ke', 'I think that', 'MUH-nay LAA-gay chhay kay'),
        w('કારણ કે', 'kāraṇ ke', 'because', 'KAA-ruṇ kay'),
        w('મારા મતે', 'mārā mate', 'in my opinion', 'MAA-raa MUH-tay'),
        w('જો … તો', 'jo … to', 'if … then', 'jo … toe'),
        w('જરૂરી', 'jarūrī', 'necessary, important', 'juh-ROO-ree'),
      ],
      sents: [
        s('મને લાગે છે કે એ સાચું છે.', 'mane lāge chhe ke e sāchuṁ chhe.', 'I think that’s true.'),
        s('હું નહીં આવું, કારણ કે મારે કામ છે.', 'huṁ nahīṁ āvuṁ, kāraṇ ke māre kām chhe.', 'I won’t come, because I have work.'),
        s('જો વરસાદ પડશે, તો આપણે ઘરે રહીશું.', 'jo varsād paḍshe, to āpaṇe ghare rahīshuṁ.', 'If it rains, we’ll stay home.'),
        s('મારા મતે ગુજરાતી શીખવું બહુ જરૂરી છે.', 'mārā mate gujarātī shīkhvuṁ bahu jarūrī chhe.', 'In my opinion, learning Gujarati is very important.'),
      ],
      grammar: { kind: 'grammar', title: 'Linking ideas',
        body: 'કે joins “I think / I know” to the rest of the sentence. કારણ કે gives a reason. જો … તો sets up a condition. These three let you say almost anything.',
        examples: [['મને ખબર છે કે …', 'mane khabar chhe ke …', 'I know that …'], ['… કારણ કે …', '… kāraṇ ke …', '… because …'], ['જો … તો …', 'jo … to …', 'if … then …']] } },
  ]},
  { id: '6b', title: 'Culture in conversation', gu: 'સંસ્કૃતિ', lessons: [
    { id: 'L44', title: 'Festivals', gu: 'તહેવાર', mins: 10,
      can: 'Greet people at festivals and talk about what you do.',
      words: [
        w('દિવાળી', 'divāḷī', 'Diwali', 'di-VAA-ḷee'),
        w('સાલ મુબારક', 'sāl mubārak', 'Happy New Year (Gujarati)', 'SAAL moo-BAA-ruk', 'Said on બેસતું વર્ષ, the day after Diwali. Formal: નૂતન વર્ષાભિનંદન.'),
        w('નવરાત્રિ', 'navrātri', 'Navratri', 'nuv-RAA-tri'),
        w('ગરબા', 'garbā', 'garba (dance)', 'GUR-baa', 'You “play” garba: ગરબા રમવા.'),
        w('ઉત્તરાયણ', 'uttarāyaṇ', 'Uttarayan (kite festival)', 'ut-tuh-RAA-yuṇ', 'January 14 — rooftops full of kites.'),
      ],
      sents: [
        s('સાલ મુબારક!', 'sāl mubārak!', 'Happy New Year!'),
        s('નવરાત્રિમાં અમે ગરબા રમીએ છીએ.', 'navrātrimāṁ ame garbā ramīe chhīe.', 'During Navratri we play garba.'),
        s('ઉત્તરાયણમાં બધા પતંગ ચગાવે છે.', 'uttarāyaṇmāṁ badhā pataṅg chagāve chhe.', 'On Uttarayan everyone flies kites.'),
        s('દિવાળીમાં અમે દીવા કરીએ છીએ.', 'divāḷīmāṁ ame dīvā karīe chhīe.', 'At Diwali we light diyas.'),
      ],
      grammar: { kind: 'culture', title: 'New Year visits',
        body: 'On બેસતું વર્ષ families visit elders, touch their feet (પગે લાગવું), and say સાલ મુબારક. Elders give આશીર્વાદ — and often a little money for the kids.',
        examples: [['સાલ મુબારક, દાદા!', 'sāl mubārak, dādā!', 'Happy New Year, Dada!'], ['સુખી રહો.', 'sukhī raho.', 'Be happy. (a blessing)']] } },

    { id: 'L45', title: 'At the mandir', gu: 'મંદિરમાં', mins: 10,
      can: 'Talk about darshan, aarti and prasad, and greet elders there.',
      words: [
        w('દર્શન', 'darshan', 'darshan (seeing the deity)', 'DUR-shun'),
        w('આરતી', 'ārtī', 'aarti', 'AAR-tee'),
        w('પ્રસાદ', 'prasād', 'prasad (blessed food)', 'pruh-SAAD'),
        w('પગે લાગવું', 'page lāgvuṁ', 'to touch (an elder’s) feet', 'PUH-gay LAAG-vuṁ'),
        w('આશીર્વાદ', 'āshīrvād', 'blessing', 'aa-SHEER-vaad'),
      ],
      sents: [
        s('ચાલો, દર્શન કરવા જઈએ.', 'chālo, darshan karvā jaīe.', 'Come, let’s go for darshan.'),
        s('આરતી કેટલા વાગ્યે છે?', 'ārtī keṭlā vāgye chhe?', 'What time is the aarti?'),
        s('દાદાને પગે લાગ.', 'dādāne page lāg.', 'Touch Dada’s feet.'),
        s('સુખી રહો, બેટા.', 'sukhī raho, beṭā.', 'Be happy, dear. (blessing)'),
      ],
      talk: { who: 'aunty', ctx: 'You touch an elder aunty’s feet after aarti.', gu: 'સુખી રહો, બેટા!', tr: 'sukhī raho, beṭā!', en: 'Be happy, dear!',
        o: [['જય શ્રી કૃષ્ણ, માસી.', 'jay shrī krishṇa, māsī.', 'Jay Shri Krishna, Masi.', true, 'Graceful.'],
            ['તમે પણ સુખી રહો.', 'tame paṇ sukhī raho.', 'You be happy too.', false, 'Blessings flow from elders — you don’t bless them back.'],
            ['બસ, બહુ થયું.', 'bas, bahu thayuṁ.', 'Enough already.', false, 'Very rude here!']] } },

    { id: 'L46', title: 'Talking about your life', gu: 'મારી વાત', mins: 12,
      can: 'Explain your goals and feelings in longer sentences.',
      words: [
        w('વિશે', 'vishe', 'about', 'VI-shay'),
        w('ઇચ્છા', 'ichchhā', 'wish, desire', 'ICH-chhaa'),
        w('અનુભવ', 'anubhav', 'experience', 'UH-noo-bhuv'),
        w('વાત', 'vāt', 'talk, matter', 'vaat', 'વાત કરવી = to talk.'),
        w('હજી', 'hajī', 'still, yet', 'HUH-jee'),
      ],
      sents: [
        s('મારી ઇચ્છા છે કે હું બા સાથે ગુજરાતીમાં વાત કરું.', 'mārī ichchhā chhe ke huṁ bā sāthe gujarātīmāṁ vāt karuṁ.', 'My wish is to talk with Ba in Gujarati.'),
        s('હું હજી શીખું છું.', 'huṁ hajī shīkhuṁ chhuṁ.', 'I’m still learning.'),
        s('આ અનુભવ બહુ સરસ હતો.', 'ā anubhav bahu saras hato.', 'This experience was really nice.'),
        s('મને તમારા વિશે કહો.', 'mane tamārā vishe kaho.', 'Tell me about yourself.'),
      ],
      read: { title: 'A letter to Ba',
        lines: [['વહાલાં બા,', 'vahālāṁ bā,', 'Dear Ba,'],
                ['હું હવે ગુજરાતી શીખું છું.', 'huṁ have gujarātī shīkhuṁ chhuṁ.', 'I’m learning Gujarati now.'],
                ['મારી ઇચ્છા છે કે હું તમારી સાથે ફોન પર ગુજરાતીમાં વાત કરું.', 'mārī ichchhā chhe ke huṁ tamārī sāthe fon par gujarātīmāṁ vāt karuṁ.', 'My wish is to talk with you on the phone in Gujarati.'],
                ['હજી ભૂલો થાય છે, પણ મજા આવે છે.', 'hajī bhūlo thāy chhe, paṇ majā āve chhe.', 'I still make mistakes, but it’s fun.'],
                ['ધ્યાન રાખજો. જય શ્રી કૃષ્ણ!', 'dhyān rākhjo. jay shrī krishṇa!', 'Take care. Jay Shri Krishna!']],
        qs: [{ q: 'What does the writer wish for?', o: ['To talk with Ba on the phone in Gujarati', 'To visit India', 'To learn to cook'], a: 0 },
             { q: 'How does the writer feel about mistakes?', o: ['They still happen, but it’s fun', 'Embarrassed', 'They don’t make any'], a: 0 }] } },
  ]},
]},
];
